### ISSUE TITLE
Could not find required mod: adorn requires {libcd @ [^2.0.0]}

### ISSUE THREAD

**Issue by seanimusprime** [Juuxel/Adorn#103]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.11.0 for 1.16.2
- Minecraft: 1.16.2
- Fabric Loader: Latest for 1.16.2
- Fabric API: Latest for 1.16.2

### Describe the bug
Updated to 1.16.2 and updated all my mods. Now when I try to launch I'm getting this error "Could not find required mod: adorn requires {libcd @ [^2.0.0]}" even though the latest version of libcd is installed (3.0.2+1.16.2). It was working fine on 1.16.1

### To Reproduce
1. Start Minecraft

**Comment by Juuxel** [comment]
Fixed in 1.11.1.
