### ISSUE TITLE
Sitting in chair/table glitch

### ISSUE THREAD

**Issue by noonononnonnoo** [Juuxel/Adorn#106]
When clicking on a chair to sit in it, the moving arm animation plays when you click, but right before sitting the first 2 frames of the moving hand animation play continuously, and after about 2 seconds of the frames playing, you finally go into the chair/table.

**Comment by Juuxel** [comment]
Do you have Immersive Portals installed?

**Comment by noonononnonnoo** [comment]
Yes, I do.

**Comment by Juuxel** [comment]
In that case this is a duplicate of #33.
