### ISSUE TITLE
"cotton-cauldron" crash

### ISSUE THREAD

**Issue by Zarpyk** [Juuxel/Adorn#109]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.11.1
- Minecraft: 1.16.3
- Fabric Loader: 0.10.2+build.210
- Fabric API: fabric-api-0.24.1+build.412-1.16

### Describe the bug
Crash when start

### To Reproduce
1. Start the game

### Additional context *(Optional)*
Crash Report & Log: https://gist.github.com/GuerreroCraft61/f0e9413dd7b0a3e38f37ad10d6b1385b
(Vanilla-Hammers have the same problem)

**Comment by Juuxel** [comment]
Not an Adorn bug. Cotton is outdated and doesn't support the newest version of LibCD, which Adorn uses.
