### ISSUE TITLE
Forge Version Remake

### ISSUE THREAD

**Issue by bingling-sama** [Juuxel/Adorn#110]
# Forge Version Remake
Hi there   
There is many Minecraft player in my country--China like your mod **Adorn**   
But **Adorn** is an **Fabric** mod   
And there are a lot of player want a **Forge** version   
So if you won't make a **Forge** version   
May I make it ?

**Comment by lazytspo** [comment]
yes. you can do it

**Comment by Juuxel** [comment]
Adorn has a Forge version now -- check out the releases on Github.
