### ISSUE TITLE
[1.16.3] Advancement not localized - [advancements.adorn.stone_torch.title]

### ISSUE THREAD

**Issue by ProsperCraft** [Juuxel/Adorn#113]
### Versions of Minecraft, Fabric and Adorn
- Adorn: Adorn-1.11.1+1.16.3
- Minecraft: 1.16.3

### Describe the bug
in discord from our discord link mod -  ServerLink: Duct_Butter has made the advancement [advancements.adorn.stone_torch.title]

**Comment by Juuxel** [comment]
This is a limitation of Fabric API. Its resource loader doesn't load any language files on the server, so the advancements won't have translations either.
