### ISSUE TITLE
NullPointerException log spam

### ISSUE THREAD

**Issue by florensie** [Juuxel/Adorn#114]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.11.1
- Minecraft: 1.16.3
- Fabric Loader: 0.10.6+build.214
- Fabric API: 0.25.0+build.415-1.16

### Describe the bug
Excessive spamming of NullPointerExceptions originating from `client.LivingEntityMixin`: https://github.com/Juuxel/Adorn/blob/a7d63fb47f8814a5adbba032c6b8adf1aa22962c/src/main/java/juuxel/adorn/mixin/client/LivingEntityMixin.java#L28

### To Reproduce
This was happening on AOF3 version 2.3.0. I haven't checked but I think the spamming happens only while lying down in a bed.

### Expected behavior
Nice and clean logs ;)

### Additional context
Game log: https://paste.ee/p/ERSe5
I'm not sure if the JVM crash at the end has to do with this issue.

**Comment by Juuxel** [comment]
Oh, that was some weird code. Fixed in dev.
