### ISSUE TITLE
When sitting on the chairs there is 3 seconds "cooldown" where the screen is black like when you are inside a block

### ISSUE THREAD

**Issue by K0-RR** [Juuxel/Adorn#115]
- Adorn: 1.12.0 
- Minecraft: 1.16.4
- Fabric Loader: 0.10.6
- Fabric API: 0.25.4
https://ibb.co/WK6sb6M

**Comment by Juuxel** [comment]
Do you have Immersive Portals installed?

**Comment by K0-RR** [comment]
No.

**Comment by Juuxel** [comment]
Oh dear. It looks like I've made the bug happen without IPortals when "fixing" it 🤦
