### ISSUE TITLE
Adorn Items are present in the "Decorative Items" Creative Menu Tab as well as in Adorn's own Creative Menu Tab

### ISSUE THREAD

**Issue by JoelZBub** [Juuxel/Adorn#118]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.12.1 for 1.16.3/4
- Minecraft: 1.16.4
- Fabric Loader: 0.10.8
- Fabric API: 0.26.3+1.16
- Kotlin: 1.4.0+build.1

### Describe the bug
Adorn Items are present in the "Decorative Items" Creative Menu Tab as well as in Adorn's own Creative Menu Tab.
This makes the Decorative Items tab feel cluttered and seems unnecessary.

### To Reproduce
1. Install Adorn and dependencies
2. Enter Creative Gamemode
3. Open Inventory
4. Look at "Decorative Items" tab, scroll down, then cycle thru tabs to Adorn tab.

### Expected behavior
Adorn items would all be located only in their respective inventory tab

### Additional context *(Optional)*
Screenshots:
https://gyazo.com/1f61687e3dabd985d469c5fd35001dc2

https://gyazo.com/a3131c172ad6341da0fcd81e940d4126

**Comment by Juuxel** [comment]
This is intended. Adorn's items are a mix of decoration and misc items so they're in those tabs, but they're also available collected in one creative tab.

**Comment by JoelZBub** [comment]
Can you add a config option for people who disagree with this, as it breaks conventions of nearly every mod ever made? Thanks.

**Comment by Juuxel** [comment]
Sure, that sounds fine. I'll add it in the next update.

**Comment by JoelZBub** [comment]
Thank you :D
