### ISSUE TITLE
Cannot remove trading table.

### ISSUE THREAD

**Issue by ElaxResources** [Juuxel/Adorn#119]
I'm on a server and I can't seem to be able to remove the table any way.

**Comment by Juuxel** [comment]
You can only break tables you've placed yourself. (You can change this from the config file. Note that it has to be changed from both the client and the server.)

If you're an operator, you can also `/setblock` it away.

**Comment by ElaxResources** [comment]
Only as the user changed the config value "protectTradingStations" to false o and it worked.

**Comment by Juuxel** [comment]
Alright, I'll close this issue then.
