### ISSUE TITLE
Can not find required mod LibCD

### ISSUE THREAD

**Issue by InkDragon** [Juuxel/Adorn#123]
### Versions of Minecraft, Fabric and Adorn
- Adorn: Adorn-1.12.2+1.16.4
- Minecraft: 1.16.4
- Fabric Loader: 0.10.8
- Fabric API: fabric-api-0.28.3+1.16

### Describe the bug
Receive the error: Can not find required mod LibCD @[^2.0.0|| ^3.0.3], game wont load. Have libcd-3.0.2+1.16.2 downloaded in the mods folder for [Vanilla Hammers](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers)

### To Reproduce
install the following mods & attempt to launch game

- Adorn-1.12.2+1.16.4
- fabric-api-0.28.3+1.16
- fabric-language-kotlin-1.4.0+build.1
- libcd-3.0.2+1.16.2
- modmenu-1.14.13+build.19
- vanilla-hammers-3.0.1-1.16.3

### Expected behavior
the game should launch to the title screen

### Additional context *(Optional)*
this is the first time I've tried fabric so -shrugs- I have no idea what's happening

**Comment by Juuxel** [comment]
> Have libcd-3.0.2+1.16.2 downloaded

Adorn needs LibCD 3.0.3 if you're using LibCD 3.x.y versions. To fix this, you can just remove the LibCD jar from your mods directory since Adorn already includes LibCD 3.0.3.
