### ISSUE TITLE
Significant FPS Drop with mod installed

### ISSUE THREAD

**Issue by MechanosG** [Juuxel/Adorn#132]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.12.2
- Minecraft: 1.16.4
- Fabric Loader: 0.10.8
- Fabric API: 0.28.3

### Describe the bug
When I add Adorn to my modpack, my FPS mysteriously seems to cap itself at about 40.  It can go below that cap during lag spikes or loading, but it will never go above it, even if I wall myself into a small area.  If I disable Adorn and reload the modpack, FPS uncaps and sits at about 50-55 in a wooded area, going above 70+ if I enter an indoors area.

### To Reproduce
1. Have access to my modpack (190'ish mods, currently in private testing, but I can get you an export of the next release should you want to test it)
2. Add Adorn
3. Create a new game, wait for chunk loading and FPS to stabilize, look in a direction, take note of FPS, save and quit. 
4. Disable/remove Adorn.  Load up the previous save.  Wait for FPS to stabilize looking in the same direction, note FPS increase, save and quit.
5. Re-add Adorn, load up previous save, wait for FPS to stabilize, take note of FPS drop just to be sure.

### Expected behavior
Expected behavior would be to no significant FPS loss, at least until I place a lot of the blocks or something.

### Additional context *(Optional)*
My modpack is sitting at about 190 mods and I've seen one other mod cause this exact FPS drop too (Minegate - MoreBlocks).  I left a comment on that mod's curseforge page, and the author seemed to be stumped, suggesting that maybe I just have too many blocks added.  But since then, I've added several large mods like Astromine, with no change in FPS.  So the only hint I have, is whatever Adorn and Minegate have in common, whether it's simply just pushing a specific resource over the edge, or maybe something else, like maybe an interaction with Canvas or a connected texture mod?  I'm just guessing at this point.  If you have any theories or need any additional information, please lemme know.

Also I did test without Canvas and the connected texture mods.  Without Canvas my fps dropped pretty massively, so I was unable to accurately test it.  Without the connected texture mods, I got about 2-5 extra FPS.

**Comment by Juuxel** [comment]
I'd suspect that the culprit in this case are all the blocks added by Adorn. AFAIK Adorn adds lots more block states compared to Astromine, which consume a lot of memory. Your lag issues might be caused by JVM freeing up memory more often.

Adorn's memory use can be slightly reduced by disabling the compatibility modules in `config/Adorn.json5`. Alternative, you can try allocating more RAM.
