### ISSUE TITLE
adorn requires {libcd @ [^2.0.0 || ^3.0.3]}

### ISSUE THREAD

**Issue by srnyx** [Juuxel/Adorn#133]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.13.0
- Minecraft: 1.16.5
- Fabric Loader: No clue, latest probably
- Fabric API: 0.29.4

### Describe the bug
When I try loading the mod on my server I get this error: `Could not find required mod: adorn requires {libcd @ [^2.0.0 || ^3.0.3]}`

### To Reproduce
1. Install latest Adorn version
2. Install latest LibCD version
3. Use on a server

### Expected behavior
The server shouldn't crash and should start normally

**Comment by Juuxel** [comment]
You should remove any manually added LibCD jars from your mods directory. Adorn bundles the actual latest version itself (the latest version is not on Curseforge).
