### ISSUE TITLE
Adorn:Biomemakeover items not in game

### ISSUE THREAD

**Issue by pjlasl** [Juuxel/Adorn#135]
### Versions of Minecraft, Fabric and Adorn
- Adorn: latest
- Minecraft: latest
- Fabric Loader: latest
- Fabric API: latest

### Describe the bug
I have Adorn and Biomemakeover installed. I am unable to craft any of the adorn/biomemakeover items list posts, platforms, etc. 
I also have REI installed and they don't show up there either.

**Comment by Juuxel** [comment]
They're not yet released in any Adorn build. They'll come in Adorn 1.14, together with some other mod compat updates.

**Comment by pjlasl** [comment]
thanks for the explanation :).
I built a script with KubeJS that adds recipes to Charm's woodcutter. Everything was working except for Biomemaker.
Look forward to the update.
