### ISSUE TITLE
Could not find required mod: adorn requires {jankson @ [^3.0.0]}

### ISSUE THREAD

**Issue by Cwcat232** [Juuxel/Adorn#136]
**Versions of Minecraft, Fabric and Adorn**
Adorn: 1.13.0
Minecraft: 1.16.5
Fabric Loader: 0.11.1
Fabric API: 0.30.5

**Describe the bug**
Whenever I attempt to open Minecraft, my Fabric crashes and gives the error message _Could not find required mod: adorn requires {jankson @ [^3.0.0]}_ 

To Reproduce

1. Download Adorn and required dependencies (+required dependencies for each of those separately) 
2. Install Fabric for 1.16.5
3. Open Minecraft with Fabric 1.16.5
4. Receive error message for Adorn
5. Remove Jankson and retry opening MC
6. Receive error message again
7. Reinstall Jankson into mod folder, open Fabric/MC again, and receive the same error message 

**Expected behavior**

Expected behavior is for MC/Fabric to open and be able to play. 

**Additional context (Optional)**
My mod folder does have a few other mods in it but I have received no errors or messages about those mods. 
Other mods include: 
-Oh The Biomes You'll Go
- Terrestria 
- Traverse
- Placeable Items 
- Campanion

**Comment by Juuxel** [comment]
You should not have a Jankson jar in your mods directory. The correct version of jankson is bundled within Adorn, so if you don't have a Jankson jar in `mods`, it should run just fine.

> Download Adorn and required dependencies (+required dependencies for each of those separately)

Adorn's required dependencies (Fabric API and Fabric Language Kotlin) don't have any required dependencies, though. Make sure you haven't downloaded LibCD, LibGui or Jankson manually.

**Comment by Juuxel** [comment]
There hasn't been any response in almost 4 months. If you have any questions, feel free to open another issue.
