### ISSUE TITLE
Connecting fence posts?

### ISSUE THREAD

**Issue by AllegoricSiren** [Juuxel/Adorn#14]
This is really dumb and I feel dumb, but how the heck do I connect the fence posts? Whenever I craft a fence and place them they don’t connect to each other. I tried sticks, wood, logs, anything that could probably connect them.

**Comment by Juuxel** [comment]
The vanilla fences should connect just fine (at least Adorn doesn't touch those), and Adorn's posts are not supposed to connect to anything.

**Comment by AllegoricSiren** [comment]
I made vanilla fences and they aren’t connecting. I know for sure I’m using just regular fences. Any advice on how to fix this problems or any solutions to try?

**Comment by Juuxel** [comment]
Okay, so it's not an Adorn bug. Could you post your full modlist here? Also, when you look at fences with F3, does it say `#minecraft:fences` on the right side under "Targeted block"?

**Comment by AllegoricSiren** [comment]
Alright so I figured it out because my mod list is literally every single mod that’s currently on fabric basically lol. verticality doesn’t like the fence post but I think it’s their mod not yours. Sorry for bugging you and all that. If you still want to see if it is your mod you can check it out but once I removed the mod fences acted like normal. Again sorry I appreciate your time.

**Comment by Juuxel** [comment]
Okay, good to know that you found the cause.
