### ISSUE TITLE
Chair drops multiple chairs

### ISSUE THREAD

**Issue by d4rkm0nkey** [Juuxel/Adorn#140]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.13.0
- Minecraft: 1.16.5
- Fabric Loader: 0.11.1
- Fabric API: 0.30.3

### Describe the bug
When I destroy a chair with an axe, two instead of one chairs are dropped.

### To Reproduce
1. Place a chair in survival (stripped spruce wood chair).
2. Destroy it with an axe.
3. Get two chairs.
4. Get two chairs?

### Expected behavior
You should only get one chair otherwise you can produce a lot of chairs without using any material.

**Comment by d4rkm0nkey** [comment]
This doesn't happen for tables. I tested without an axe and it drops two chairs as well.

**Comment by Juuxel** [comment]
This seems to be a bug with the Extra Pieces compatibility options. I'll have to take a look at this at some point.

**Comment by d4rkm0nkey** [comment]
That could be true. I have the mod extra pieces installed.
