### ISSUE TITLE
Support for Modded Chests in recipes

### ISSUE THREAD

**Issue by IdrisQe** [Juuxel/Adorn#143]
I'm not entirely sure how this could be done easily, given every mod seems to use different tags for their chests, but to use an example, SimpleBackpacks seems to accept BetterEnd chests despite them using different tags as far as I can tell, and not having any explicit integration between the two mods, however Adorn checks very specifically for just vanilla chests, not even using a tag, so they're completely incompatible.

Some Fabric mods with chests that don't work in Adorn recipes include:
-BetterNether
-BetterEnd
-Bewitchment
-Charm
-Sakura Rosea

**Comment by NovaLynxie** [comment]
I've seen the exact same occur in the forge version of Adorn.
Some Forge mods which add their own chests include the following: (Quark/Charm have forge versions)
Quark, Charm, Terrain Incognita, Autumity and Environmental.

**Comment by NovaLynxie** [comment]
Depending on how the mod's implement their chests, it could look for certain tags the mod loaders recognise.
Considering it is using vanilla chests which are wooden, for forge it could be done via forge:chests/wooden as an example. I don't know how fabric does it but could be done in a similar way.

**Comment by Juuxel** [comment]
This is probably easier to fix on Forge. I'm not sure if there's a standardised tag for these on Fabric (though `#c:chests` might be), but Forge likely has something like `#forge:chests`.

**Comment by NovaLynxie** [comment]
It has forge:chests and forge:chests/wooden. I think the forge:chests/wooden one only looks for wooden ones whereas forge:chests will use any available chest.
