### ISSUE TITLE
Block state desync bug

### ISSUE THREAD

**Issue by coffeeemu873761** [Juuxel/Adorn#149]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.13.0
- Minecraft: 1.16.5
- Fabric Loader: 0.7.2
- Fabric API: 0.32.0

### Describe the bug
the textures of the blocks in the mod are glitched

### To Reproduce
1. enter game with mod
2. look at item of mod
3. has different texture

### Expected behavior
the game should display the modded block correctly. This mod is on a server and others on the server can see the correct texture except I cannot.
![2021-03-22_11 24 48](https://user-images.githubusercontent.com/81179105/112023458-442d9c00-8b01-11eb-8e01-d809a5913c0d.png)
this is how it looks with a stone torch on left and shelf on right

### Additional context *(Optional)*
![Screenshot 2021-03-22 112611](https://user-images.githubusercontent.com/81179105/112023637-6d4e2c80-8b01-11eb-9926-9e766ff9fa43.png)
this is everything in my mods folder

**Comment by Juuxel** [comment]
Please make sure you have the exact same set of mods (excluding client-only or server-only mods like Mod Menu) as the server has. These issues are usually caused by the two having a different set of mods.

**Comment by coffeeemu873761** [comment]
I have copied and pasted the mods from the server folder into my client folder, and it is still happening.

**Comment by coffeeemu873761** [comment]
after uninstalling minecraft and deleting all files, and then reinstalling everything. It works
