### ISSUE TITLE
Picket fences do not connect correctly

### ISSUE THREAD

**Issue by heyjudek** [Juuxel/Adorn#150]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.13
- Minecraft: 1.16.5
- Fabric Loader: 0.11.3
- Fabric API: 0.32.0+1.16

### Describe the bug
Picket fence doesn't connect three ways (or probably four too)
![2021-03-23_17 46 10](https://user-images.githubusercontent.com/74119394/112185394-78d44d00-8c00-11eb-9888-2034c6eae132.png)

**Comment by Juuxel** [comment]
This is the intended behaviour of picket fences.
