### ISSUE TITLE
Not compatible with Biomes You’ll Go mod

### ISSUE THREAD

**Issue by sunny-day123** [Juuxel/Adorn#154]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.12.2
- Minecraft: 1.16.5
- Fabric Loader: 0.11.3
- Fabric API: 0.32.5
- BYG: 1.1.7

### Describe the bug
Please make this mod compatible with BYG (Biomes You’ll Go). I’m trying to run this mod and BYG at the same time, but Minecraft lags, stops responding, and crashes every time. As soon as I get to the Menu page (the one that says Singleplayer, Multiplayer) it lags and a few seconds later it crashes. It stops respond even before I even click “Play Selected World.” I don’t have this problem with my other mods and I’ve never experienced BYG causing my game to crash like this.

### To Reproduce
1. Download BYG Fabric 1.1.7 https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric
2. Add it your mods folder along with Adorn 1.12.2
3. Launch Minecraft (I launch it through MultiMC but I’m sure that no matter what launcher you use this bug will still happen)
4. Stop responding & crash

### Expected behavior
The main pages with the Singleplayer and Multiplayer options will lag and after a few seconds Minecraft will completely crash or stop responding.

### Additional context *(Optional)*
I’m 100% sure that BYG is the mod that Adorn is incompatible with this because I turned off all of my other mods and BYG was the only one I kept enables and it still stopped responding and crashed. I turned off ALL of my mods (including BYG) and did NOT have this problem.

Please fix this if you can lol, I’d really like to play BYG and Adorn simultaneously because BYG is my most important mod and I just really want furniture in my house lol

And I DO have BYG compatibility enabled in the config file, yet it still doesn’t work.

**Comment by sunny-day123** [comment]
Update: I was able to get into the world but I’m getting 1 frame every 3 seconds (I usually don’t get lag problems, my FPS is usually 60-70). Is there a way that this can be fixed?

**Comment by Juuxel** [comment]
Could you post the crash log (for example as a Github Gist)? I can't really help without it.

Also, please try reproducing with the latest Adorn version, you're using an older version from last year.

**Comment by sunny-day123** [comment]
Ok, I reproduced it with the latest Adorn version. 

Did I do this correctly? It's the Crash Report given to me by MultiMC.
https://gist.github.com/sunny-day123/b217981ff82d6753770a8b25106effaa

**Comment by Juuxel** [comment]
Yeah, thanks. Your Adorn config file seems to be corrupted (invalid JSON5 format), try deleting `config/Adorn.json5` and see if it still happens.

**Comment by sunny-day123** [comment]
I did it and it stopped crashing but it still lags to the point where I can’t click Singleplayer or Multiplayer. Usually my computer doesn’t lag and if it does it only happens when I’m already in the world, not on the menu screen.

**Comment by Juuxel** [comment]
I'm suspecting that this might be a RAM issue. With both Adorn and BYG installed, as well as their compatibility mode enabled, there are hundreds of new block states and their models taking up memory. I think the lag is caused by the JVM's garbage collector having to pause the game more often to free up RAM.

If you can, try allocating some more RAM to the game or alternatively setting the BYG compat to false in Adorn's config file.

**Comment by sunny-day123** [comment]
Thank you so much for all of your help! I did both of these and it worked- no more lag!

**Comment by Juuxel** [comment]
No problem! Glad it works :^)
