### ISSUE TITLE
Installing Adorn with bare minimum requirements causes infinite loading loop

### ISSUE THREAD

**Issue by Athrizel** [Juuxel/Adorn#155]
I have the main requirements to run adorn (I.E. Fabric API and Fabric Language Kotlin) but when I try to load the game, the launcher will get stuck in an infinite loading loop where a bunch of errors get spit out, then it tries to load the shulker box texture (for some reason) and then has an error loading the last version of it, then the load process resets to half loaded and then loops from there, getting back to the shulker box textures before throwing up the same error and looping.

I really want to be able to run this mod but at the current time I'm not able to make it work, I'm loading this using an MultiMC instance if that makes a difference. I only bring this up because I noticed that WorldEdit was also having loading issues with the 1.16 version if you used a MultiMC instance.

I hope this gets looked into and is fixed sooner rather than later.

**Comment by Juuxel** [comment]
This is really odd, never experienced myself (I use MultiMC for playing/testing myself). Could you post the full game log (`logs/latest.log` in the MMC instance game directory) from when this happens on [Gist](https://gist.github.com) or another paste service?

**Comment by Athrizel** [comment]
ok https://gist.github.com/Athrizel/deac64d2dd44e2eb4a11a5b877f4d94d

Hope this helps, like I said in it's description, it looped around 5 times before I realized what had happened. I should mention I have no problems loading this instance normally, it's only when I install adorn that this kicks up for some reason.

**Comment by Juuxel** [comment]
```
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
```
^ There's your problem. Adorn on its own adds a lot of block states (whose models especially like to take up RAM), but you also have Towelette and BYG installed which makes Adorn create hundreds of extra block states for mod compatibility.

I'd try increasing the RAM allocated to Minecraft, or going to Adorn's config file (`config/Adorn.json5`) and disabling Towelette and/or BYG compat (Towelette compat is the main offender here honestly).

**Comment by Athrizel** [comment]
I honestly didn't see that, increasing ram helped, thanks.
