### ISSUE TITLE
Lava textures display incorrectly when directly behind glass block

### ISSUE THREAD

**Issue by nicwatson** [Juuxel/Adorn#16]
Minecraft 1.14.1
Adorn 1.0.1 for 1.14.1
Dependency versions:
Fabric API 0.3.0 pre-build 157a for 1.14.1 (latest 1.14.1 version)
Fabric Kotlin 1.3.30 build2

(Also previously observed on Adorn 0.1.3 for 1.14, w/ Fabric API 0.27 build 127, Fabric Kotlin 1.3.30)

When a block of lava (source or flowing) is placed directly behind a block of glass (normal or stained), the lava texture (the surface directly against the glass) does not display correctly. Instead, a non-textured solid-colour surface is shown, which cycles through shades of orange in accordance with lava's standard animation (see pic 1).

![2019-05-26_13 42 18](https://user-images.githubusercontent.com/587252/58385507-76cae400-7fbf-11e9-960d-f4aadb46eeef.png)

Lava remains luminous as normal. Only side textures are affected -- lava above glass seen from below looks normal. All lava depths appear to be affected.

This occurs with no other mods active. However, as a possible additional data point (maybe knowing about mod interactions will help identify the underlying issue?), if I do throw Blockus (1.1.10) into the mix, the texture turns black and no shade-cycling is observed (pic 2).

![2019-05-26_13 49 24](https://user-images.githubusercontent.com/587252/58385573-56e7f000-7fc0-11e9-9ea5-f240ca108f2f.png)

Under some conditions, it appears grey instead of black -- e.g. behind white stained glass. It also appears grey instead of black when placed with a larger set of mods I use, but I have not isolated which specific combination of mods has that effect.

(Otherwise, a fantastic mod - thanks!)

**Comment by Juuxel** [comment]
Hm, Adorn itself shouldn't affect this; it might be related to Towelette. I'll need to investigate this.

**Comment by nicwatson** [comment]
Thanks for the response. Looks like you're correct - I reproduced the issue with just Towelette 1.5.2, which is the version packaged with Adorn. 

It seems to be fixed with Towelette 1.6.0. Throwing that in the mods folder provides a workaround that makes the lava look right again (although I haven't tested if that affects waterlogging of Adorn blocks).

**Comment by Juuxel** [comment]
It shouldn't. I'll update Towelette in an update.
