### ISSUE TITLE
Add support for DashLoader

### ISSUE THREAD

**Issue by QPCrummer** [Juuxel/Adorn#160]
Link: https://github.com/alphaqu/DashLoader
The devs said that they couldn't add support for your model type, but they said there was an api that could add support. DashLoader is a mod which drastically decreases loading time, usually by more than 10X. I does this by caching necessary info on load up. I am running AOF3, and I want to be able to add this mod, however Adorn is one of the few mods that isn't supported.

**Comment by QPCrummer** [comment]
They said they had an API for mods to be compatible

**Comment by Juuxel** [comment]
There's no documentation on this API available at all, so I won't be adding this.

**Comment by alphaqu** [comment]
Yes, the api at this point can be called non-existent. The current caching system has it sortof ready but the mod detection and the declaration to the serializer does not exist.

**Comment by alphaqu** [comment]
@Juuxel The API has been added in now. It would be great if you were able to test it out and give me some feedback as adorn uses kotlin and I really wanna know how it affects things. https://github.com/alphaqu/DashLoader/wiki/

**Comment by Juuxel** [comment]
@alphaqu Thanks for the info. I don't see how DashLoader applies to Adorn, though - Adorn only uses pure JSON models (loaded by vanilla code) and no custom `BakedModel` implementations.

**Comment by alphaqu** [comment]
Oh god it might then by kotlin

**Comment by alphaqu** [comment]
Hey after looking more into you guys are using custom Property Objects, This can be added through the API. If you need any help please DM me on discord: !alpha#2114 or if you find it more convinient do it through here.
