### ISSUE TITLE
Minecraft Crashing

### ISSUE THREAD

**Issue by ijxssie** [Juuxel/Adorn#170]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.0
- Minecraft: 1.17
- Fabric Loader: 0.15.5-1.17
- Fabric API: 0.34.9+1.17

### Describe the bug
Every time I've added this mod to my mods folder, Minecraft crashes with the Minecraft Error Code 0. 

### To Reproduce
1. Add Adorn to mods folder
2. Open and load Fabric 0.15.5-1.17 (Vanilla, no client)
3. Minecraft closes and produces the Error Code 0

### Expected behavior
Ability to run Adorn as a mod without Minecraft crashing.

**Comment by Juuxel** [comment]
Please share the full game log (in `.minecraft/logs/latest.log` right after the game crashes) on Pastebin/Github Gist or a similar paste site, so I can investigate this a bit further.

**Comment by ijxssie** [comment]
> Please share the full game log (in `.minecraft/logs/latest.log` right after the game crashes) on Pastebin/Github Gist or a similar paste site, so I can investigate this a bit further.

https://gist.github.com/ijxssie/6951c04fd15babec271fb48ce9ac738f (I believe that's what you need, if you need something else just lemme know!

**Comment by Juuxel** [comment]
This should be fixed if you install [Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin), which is Adorn's dependency.

**Comment by ijxssie** [comment]
Yes! Thank you so much!
