### ISSUE TITLE
LAN server sit bug: guests on a LAN server can forcefully teleport the Host player by shift + right-clicking a stair or sofa

### ISSUE THREAD

**Issue by ScottWDeane** [Juuxel/Adorn#172]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.0.0 + 1.17 fabric
- Minecraft: 1.17
- Fabric Loader: 
- Fabric API: 0.36.0 + 1.17

### Describe the bug
LAN server: When a guest player (not the host) shift + right-clicks a stair to sit in it, it teleports/warps the LAN host to the chair forcing them to sit in it. Does not work the other way - if the host shift + right-clicks the stair, nothing happens.

### To Reproduce
1. Open LAN game
2. Have guest join LAN game
3. Place a stair in sitting position
4. Guest presses shift + rightclick on the chair
5. Watch as host is teleported and forced to sit in the stair as a chair

### Expected behavior
I would assume only the player targeting the stair should be forced to sit in it, and not other players.

**Comment by Juuxel** [comment]
Can't reproduce.
