### ISSUE TITLE
Doesn't work on realms?

### ISSUE THREAD

**Issue by kaitlynmckay** [Juuxel/Adorn#173]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.0.0
- Minecraft: 1.17
- Fabric Loader: 0.11.6
- Fabric API: 0.36.0

### Describe the bug
Furniture wont place in minecraft realm. All items are in the game, but when placed they show up for a split second then disappear.

### To Reproduce
1. Go to minecraft realm
2. Get items in creative
3. Try placing any of the items
4. See error placing items

### Expected behavior
Items to place like normal

**Comment by Juuxel** [comment]
Realms doesn't support mods.
