### ISSUE TITLE
Kitchen Cupboard crashing game when right clicking to open

### ISSUE THREAD

**Issue by topbun92** [Juuxel/Adorn#178]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.0.0+1.17
- Minecraft: 1.17.1
- Fabric Loader: Fabric Loader 0.11.6
- Fabric API: 0.36.1+1.17

### Describe the bug
game crashes when opening kitchen cupboard storage container

### To Reproduce
1. Go to kitchen cupboard
2. right click to open
3. game crashes

### Expected behavior
expect to see inventory screen

### Additional context *(Optional)*
see attached crash log
[crash-2021-07-08_15.40.04-client.txt](https://github.com/Juuxel/Adorn/files/6787729/crash-2021-07-08_15.40.04-client.txt)

**Comment by Juuxel** [comment]
Fixed in Adorn 2.1.0.
