### ISSUE TITLE
Adorn Items not Visible when being placed into the world

### ISSUE THREAD

**Issue by DadBackFromWalmart** [Juuxel/Adorn#191]
### Versions of Minecraft, Fabric and Adorn
- Adorn: Adorn-1.14.1+1.16.5
- Minecraft: 1.16.5
- Fabric Loader: 0.11.6
- Fabric API: fabric-api-0.36.0+1.16

### Describe the bug
I am in a friends-only multiplayer server. The world is set to Survival. When I view Adorn items in inventory, recipe book, and REI item lookup, I see them as intended. However, when I place them into the world, they load as other items. For example, the Stone Torch loads as a pink carpet under a dark oak table that is waterlogged.

### To Reproduce
Steps to reproduce the behavior: ... this is actually hard because no one else on the server (5 other users) are seeing this, it's only me. I'm not the host either.

I do wonder if me having an AMD graphics card (where everyone else is on NVIDIA) plays a role?
I'm also the only one OP on the server, but I doubt that impacts this.

Alas, here's some helpful information that I can think of:

Item in Inventory:
![image](https://user-images.githubusercontent.com/61283820/126048924-7fa368fa-7031-47fe-9622-990e16485fe8.png)

Item in hotbar:
![image](https://user-images.githubusercontent.com/61283820/126048935-74f0694c-b713-430e-89cb-98d41eb0a7ad.png)

Item in Recipe Book:
![image](https://user-images.githubusercontent.com/61283820/126048949-e0d71326-161f-4e4d-92b4-179b87379eae.png)

Item in REI Search:
![image](https://user-images.githubusercontent.com/61283820/126048963-5867ca73-3793-42c6-8f8c-2f1e21646304.png)

Item in world:
![image](https://user-images.githubusercontent.com/61283820/126048966-6e55cbda-058c-4252-bf17-e2f94aa78714.png)

The above is true for most Adorn items that I've tried (some seem to load fine, others are a crapshoot).

That said, this DOES NOT occur in Single Player - only on this Multiplayer server.

Debug when looking at placed item... if that's helpful:
![image](https://user-images.githubusercontent.com/61283820/126049134-c4ade681-5e8b-4be0-b1c0-cb894f95fa58.png)

### Expected behavior
The items to place into the world as intended, visually and functionally.

### Additional context *(Optional)*
Client Mods:
![image](https://user-images.githubusercontent.com/61283820/126049159-9e5ed77d-d289-40c0-b85a-a45c6c404358.png)

Server Mods:
![image](https://user-images.githubusercontent.com/61283820/126049169-a811f42f-bde7-46a9-8df0-38c4f5282e9a.png)

Oddly, when I place the item, it places for a split second before converting to looking whack.

Video 1:
https://youtu.be/HzTfXuUWJWg

Video 2:
https://youtu.be/xbg3GR74A6Q

If there's anything more helpful I can share let me know. I'm just straight up lost here.
I'll add lastly that items from other mods all load fine.

**Comment by DadBackFromWalmart** [comment]
Also apologies in advance - I didn't realize my voice audio was so low when recording those videos until just now. Haven't done a whole lot of recording lately, but at least I think the point still gets across.

**Comment by Juuxel** [comment]
This seems like a server-client desync bug. (See #74 for example.) To fix this, make sure that your Adorn config matches the server's. Specifically the `sittingOnTables` config option* and all `compat` options must match between the sides - otherwise this issue will probably happen.

*`sittingOnTables` has been removed in the 1.17 versions of Adorn due to causing this very bug. I'd recommend updating if you can :^)

**Comment by DadBackFromWalmart** [comment]
Changed config to disallow sittingOnTables on Client side to match server settings. Fixed the issue. Thanks man! Sorry to bother.
