### ISSUE TITLE
Advancements Bug

### ISSUE THREAD

**Issue by kalinzange** [Juuxel/Adorn#192]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.1.1
- Minecraft: 1.17.1
- Fabric Loader: 0.11.6
- Fabric API: 0.37.1

### Describe the bug
Whenever you create a new world you unlock immediately achievements

### To Reproduce
Steps to reproduce the behaviour:
1. Create New SinglePlayer World
2. Chat says:

- kalinzange has made the advancement [Rocky Lighting]
- kalinzange has made the advancement [Potential for Power...]
- kalinzange has made the advancement [Bring Me Blood!]
- kalinzange has made the advancement [Day at the Market]

### Expected behaviour
No Achievements should be unlocked once you create the world

**Comment by Juuxel** [comment]
Known issue, will be fixed in the next release of Adorn.

**Comment by nnmrts** [comment]
This is still or again happening.

**Comment by kalinzange** [comment]
> This is still or again happening.

Please raise as a new issue, surely a lot of changes has returned since 2021.
