### ISSUE TITLE
Crash on load after updating to Adorn 2.1.2

### ISSUE THREAD

**Issue by RealTabman** [Juuxel/Adorn#193]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.1.2
- Minecraft:  1.17.1
- Fabric Loader:  0.11.6
- Fabric API: 0.37.1

### Describe the bug
Crash during loading, see log.
[latest.log](https://github.com/Juuxel/Adorn/files/6878117/latest.log)

### Expected behavior
No crash during load...

### Additional context *(Optional)*
No Crash before updating to Adorn 2.1.2 .
When disabling Adorn, Minecraft loads normally without crashing.

**Comment by Juuxel** [comment]
Thanks for reporting this so quickly! It'll be fixed in 2.1.3. (the cause was FabricMC/fabric-loom#448 :eyes:)

**Comment by RealTabman** [comment]
And I in turn will thank you for the quick solution :)
