### ISSUE TITLE
Stone torch can't work

### ISSUE THREAD

**Issue by Fonezang0201** [Juuxel/Adorn#194]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.14.1+1.16.5
- Minecraft: 1.16.5
- Fabric Loader: Iris-Installer-1.1.1
- Fabric API: 0.36.0+1.16

### Describe the bug
A clear and concise description of what the bug is. **If your bug is a crash, attach the full game log (found in `logs/latest.log` after the game crashes.**

The torch my friend put on the wall can be used. But I can't let it work successful.

![messageImage_1627305757504](https://user-images.githubusercontent.com/87998195/127037737-355ba83c-6184-41a1-a786-c1bb9ac9d6ca.jpg)
![messageImage_1627310602342](https://user-images.githubusercontent.com/87998195/127037747-d77e2235-655a-4444-b70c-4903a609862a.jpg)

### To Reproduce
1.  It's still ok when I make the torch.
2.  When I  put it on the wall, they become a stange structure and can't work.
3. But my friends who use the same version mod can use it.

### Expected behavior
Hope that it can be useful.

**Comment by Juuxel** [comment]
Adorn for Minecraft 1.16 is unsupported. The instructions here might solve the bug, though: https://github.com/Juuxel/Adorn/issues/74#issuecomment-881962631
