### ISSUE TITLE
Can't sit on stool, and desyncs from server.

### ISSUE THREAD

**Issue by shalestorm** [Juuxel/Adorn#196]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.1.3
- Minecraft: 1.17
- Fabric Loader: 0.11.6
- Fabric API: 0.37.1

### Describe the bug
If i right click the stools, i can just keep walking around, works as expected on chairs, but stools make me stutter for a second, then gives me full movement ability

### To Reproduce
Right click on stool
wait 1 second, then start walking around
doors will act strange, using storage blocks will ghost inventory changes.
press shift to teleport back to the stool

### Expected behavior
Right click stool
teleport to stool and be seated/unable to move
press shift to free thy self.

### Additional context *(Optional)*
doors split in half, inventory ghosting. cant hurt mobs.

**Comment by Juuxel** [comment]
Adorn doesn't have stools. Are you talking about chairs, or are these stools from another mod?

**Comment by shalestorm** [comment]
It was my server, it had some other mod on there apologies!
