### ISSUE TITLE
interesting glitch when using with arcane magic

### ISSUE THREAD

**Issue by MrPurple6411** [Juuxel/Adorn#20]
Nothing really to see in the log BUT!!!!
https://paste.ee/p/EE7Db
ohh also happened in 1.14.2

All regular grass looses its textures and is invisible until you right click on it then turns to the no texture purple box thing
![2019-07-06_18 50 06](https://user-images.githubusercontent.com/7858500/60762513-7fcbbe00-a01f-11e9-90a3-6b7cf467613a.png)

**Comment by Juuxel** [comment]
Can't reproduce with only Adorn.
