### ISSUE TITLE
Effective tool for breaking furnitures

### ISSUE THREAD

**Issue by verlixis** [Juuxel/Adorn#202]
It would be great if the furniture has an effective tool that makes breaking them faster (I suggest axes).

**Comment by Juuxel** [comment]
Good reminder, thanks! They were breakable by axes before Fabric API broke, so I need to port the functionality to 1.17.

**Comment by verlixis** [comment]
Sounds great, thank you!

**Comment by Juuxel** [comment]
Fixed in dev.

**Comment by verlixis** [comment]
Sorry to open this again, but Dark Oak Table is still left without an effective tool! (Possibly other table wood variants as well)
@Juuxel

**Comment by Juuxel** [comment]
Thanks for reporting that, I found the issue: I accidentally added all *kitchen sinks* to the table tag instead of the tables... This'll be fixed in the next release.
