### ISSUE TITLE
Adorn Stone Ladder reverts to wood texture when placed.

### ISSUE THREAD

**Issue by PuppetMasterZee** [Juuxel/Adorn#203]
### Versions of Minecraft, Fabric and Adorn
- Adorn: Adorn-2.1.3+1.17.1-fabric
- Minecraft: 1.17.1
- Fabric Loader:  0.11.6
- Fabric API: fabric-api-0.38.1+1.17

### Describe the bug
Stone ladder reverts to wood texture when placed

### To Reproduce
1. Craft a stone ladder, place any block
2. Place stone ladder on block
3. Stone ladder will still have stone ladder texture in your inventory, but will have wooden ladder texture on the block.
4. See screenshot

### Expected behavior
Expect stone ladder texture to retain the stone texture when placed.

### Additional context *(Optional)*
List of mods in pack
[ListOfMods.txt](https://github.com/Juuxel/Adorn/files/7059552/ListOfMods.txt)

Screenshot
![Adorn_Stone-Ladder_2021-08-26_06 57 17](https://user-images.githubusercontent.com/84147261/130959266-0c2c8b15-1b15-4081-b070-68ff1322e8cc.png)

**Comment by Juuxel** [comment]
The resource pack you're using overrides the vanilla ladder model to use other texture IDs, so Adorn's textures don't apply.

**Comment by PuppetMasterZee** [comment]
Thanks! I appreciate you getting back me so quickly and will hunt it down.
