### ISSUE TITLE
Can't get in to Minecraft

### ISSUE THREAD

**Issue by SmallAstronomyGremlin** [Juuxel/Adorn#205]
I can't open Minecraft when I have the Adorn mod added to Minecraft. Yes, I do have Fabric API and the other support mod, but I still can't get in. It says:
" Could not find required mod: adorn requires {fabric @ [>=0.37.2]} "
Whenever I try to play with fabric.

![Failed to launch](https://user-images.githubusercontent.com/89859134/131531230-4fbdaa3e-3efb-4e70-a14a-dfa921158d9e.png)

**Comment by Juuxel** [comment]
You need to update your Fabric API to the latest version. (Or at least FAPI 0.37.2)

**Comment by SmallAstronomyGremlin** [comment]
Oh, alright. Thank you
