### ISSUE TITLE
Adorn wants Fabric 0.37

### ISSUE THREAD

**Issue by UnusedCactus** [Juuxel/Adorn#206]
When trying to open Minecraft with the latest version of both Fabric and Adorn, Adorn does not load, and instead, asks for an earlier version of Fabric.
 **Here is the log:**
[latest.log](https://github.com/Juuxel/Adorn/files/7140063/latest.log)

**Comment by Juuxel** [comment]
Which Fabric API version are you using (the exact version number)?

**Comment by UnusedCactus** [comment]
Fabric API 0.37.0+1.17

**Comment by Juuxel** [comment]
Your Fabric API is outdated. Adorn needs Fabric API 0.37.**2** or newer (the newest is [0.40.1](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3454922)).

**Comment by UnusedCactus** [comment]
Will try that.

**Comment by UnusedCactus** [comment]
It worked! Thanks
