### ISSUE TITLE
Dupe Glitch With Trading Stations

### ISSUE THREAD

**Issue by SlimeWyboy** [Juuxel/Adorn#208]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.0.01.17
- Minecraft: 1.17
- Fabric Loader: Latest
- Fabric API: 0.36.0

### Describe the bug
easy to do trading station dupe

### To Reproduce
1. Place down a trading station
2. put the items you wanna dupe inside of it
3. place tnt or have a player beside it
4. light the tnt and open the GUI/open the GUI and have the other player break it
5. wait until the tnt has blown up the trading station and take out the items from the gui/ once the player breaks it take the items out of the gui
6. pick up and place back down the trading station
7. now you have double the items.

### Expected behavior
Its a dupe

**Comment by Juuxel** [comment]
Thanks for reporting this! It's fixed in Adorn 2.1.5.
