### ISSUE TITLE
Cloth from "Trading Station" is coming out distorted, depending on angle you're viewing from

### ISSUE THREAD

**Issue by Sinclo** [Juuxel/Adorn#218]
While playing with the trading station, we're seeing that the cloth is coming out distorted for some reason, depending on what angle you're viewing it from.  Screenshots are provided below.

[
![2021-10-24_18 25 26](https://user-images.githubusercontent.com/8661736/138617485-87f489cb-5233-4ba2-a7d2-a4ff3df885de.png)
![2021-10-24_18 36 36](https://user-images.githubusercontent.com/8661736/138617486-58d37145-c406-4dc9-970f-1c89fd76189b.png)
](url)

**Comment by Juuxel** [comment]
Please reopen this issue with one of the issue templates, or list out:

- which mod platform you're using (Forge/Fabric) + the version of forge/fabric
- which MC version you have
- which Adorn version you have

**Comment by Juuxel** [comment]
See the above comment, and if you're using Sodium on MC 1.17, updating Adorn might fix this bug.
