### ISSUE TITLE
Items disappearing in kitchen cupboards

### ISSUE THREAD

**Issue by Yogfan14** [Juuxel/Adorn#219]
### Versions of Minecraft, Forge and Adorn
- Adorn: 2.2.0+1.17.1
- Minecraft: 1.17.1
- Forge: 37.0.103

### Describe the bug
I tried to store some mod items (different mod) in a kitchen cupboard. When I went to the cupboard to retrieve these items, however, the items had vanished from the storage completely. Picking the cupboard back up did not bring these items back. Through testing, this is happening with all items, not just modded ones. 

### To Reproduce
1. Create item
2. Open cupboard, place item inside
3. Reopen cupboard. Item it now gone and irretrievable. 

### Expected behavior
I expect to open the cupboard back up and my items that I stored to be there. This clearly ain't the case.

### Additional context *(Optional)*
This is also occurring with the drawers. Basically, storage isn't working and is eating all of my items which is very annoying as someone who loves a functional kitchen to go along with my cooking mods.

**Comment by Juuxel** [comment]
Oh dear, this sounds quite major. I'll investigate this as soon as I can.

**Comment by blackeyedgamer** [comment]
Same issue here. Playing a modpack called Better Minecraft for 1.17.1 v8
If that information helps at all.
