### ISSUE TITLE
crashes straight away

### ISSUE THREAD

**Issue by kaedon142** [Juuxel/Adorn#220]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.14.2 for 1.16.5
- Minecraft: 1.16.5
- Fabric Loader: 0.11.6-1.16.5
- Fabric API: 0.34.6+ 1.16
-koltin: I've tried multiple versions
### Describe the bug
when I load mc it shows fabric launcher with says Could not find required mod: adorn requires {fabric-language-kotlin @ [^1.6.4]}
Creating Empty clause?

### To Reproduce
Steps to reproduce the behaviour:
1. Click on 'play'
2. See error

### Additional context *(Optional)*
[latest.log](https://github.com/Juuxel/Adorn/files/7457305/latest.log)

**Comment by Juuxel** [comment]
As the error says, you need to install Fabric Language Kotlin 1.6.4 or newer.

**Comment by kaedon142** [comment]
there is none

**Comment by Juuxel** [comment]
You can get 1.6.5 at least here: https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/files/3477154 (works on any mc version)
