### ISSUE TITLE
Unable to boot Minecraft with Adorn installed

### ISSUE THREAD

**Issue by Anubeia** [Juuxel/Adorn#221]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.3.0 (latest)
- Minecraft: 1.17.1
- Fabric Loader: 0.12.5 (latest)
- Fabric API: 0.42.1 (latest)

### Describe the bug
Regardless of the permutations of mods I have in my library (even if Adore is by its lonesome with the bare minimum mods to fulfil its requirements), this version appears to be consistently troublesome.

### To Reproduce
1. Have the "mods" folder set up in the manner described above.
2. Click on 'PLAY'.
3. ???
4. Profit

### Crash Report (attached file)
[crash-2021-11-07_15.35.45-client.txt](https://github.com/Juuxel/Adorn/files/7491743/crash-2021-11-07_15.35.45-client.txt)

### Expected behavior
The inverse of the events that transpired; as seen above.

### Additional context
Frankly, I wouldn't be surprised if the reason it isn't working the way it's supposed to is because of something really dumb on my end. 75% of the time, the solution for my worries is something really, really obvious... because I'm very absent-minded sometimes.

**Comment by AmonRay** [comment]
u a not alone, I have the same issue

**Comment by ChromaPIE** [comment]
Same issue.

**Comment by Juuxel** [comment]
I'll fix this ASAP. I'm actually not even sure how this code worked in the first place...
