### ISSUE TITLE
Strange bugs when enabling Adorn on the modpack (related mod: Iris)

### ISSUE THREAD

**Issue by AmibeSkyfy16** [Juuxel/Adorn#222]
### Versions of Minecraft, Fabric and Adorn
- Adorn:  Adorn-2.3.1+1.17.1-fabric.jar
- Minecraft: 1.17.1
- Fabric Loader:  0.12.3 / or also try 0.11.7 => error still
- Fabric API:  fabric-api-0.42.1+1.17.jar

### Describe the bug
When i install adorn to my curseforge profile, i have some strange bug. In the most of case, the bug is with Iris mod (see issue on github of iris: https://github.com/IrisShaders/Iris/issues/930)

### To Reproduce
I did an export of the curseforge profile. you can import it and see the error (if you disabled adorn, the error will disappear)
https://drive.google.com/file/d/1nIR1fmpcundc-Di4twBSOPakRDPoyRk4/view?usp=sharing

**Comment by Juuxel** [comment]
What exactly is the "strange bug" in question? If it's a crash, could you post the crash log?

**Comment by AmibeSkyfy16** [comment]
Crash-report: https://pastebin.com/mquFdmXb
Logs: https://pastebin.com/9M8SURsD

I launch minecraft -> and crashed (not every time the same error message)

**Comment by Juuxel** [comment]
Ugh, this crash is something I've seen before but I've never been able to reproduce it. Could you install [mixintrace](https://github.com/comp500/mixintrace) and [Crafty Crashes](https://github.com/chocohead/crafty-crashes) (especially this one is useful for me) and post the crash report then?

**Comment by AmibeSkyfy16** [comment]
crash-report https://pastebin.com/RsgaBWQN
logs https://pastebin.com/neMy0WaX
i put crafty crash jar, but i think it not loaded

**Comment by Juuxel** [comment]
Oh wow, both of them failed to apply. I can't really help with this issue right now since it seems that
- I can never reproduce it myself (although I'll try the curseforge profile to see if I can get it to reproduce with that)
- All debugging tools fail 😔

**Comment by AmibeSkyfy16** [comment]
I just made a new clean installation, I run -> and two crash (Iris GetpipeLine) and the error "adorn" the same.
my new installation is on fabric 0.12.5

I disable adorn -> minecraft runs without crash
crash-reports server: https://pastebin.com/NcJ3yB4C
crash-reports client: https://pastebin.com/pfE2E8ff
logs (lastest.txt): https://pastebin.com/jD7jjeNH

**Comment by Juuxel** [comment]
Hmm, I don't see how the client crash would be caused by Adorn but the server crash is that one crash again. I'll try to investigate this over the weekend to see which mod is breaking vanilla code.

**Comment by AmibeSkyfy16** [comment]
I informed the devs about my problem with iris on their github. 

Thanks for the work

Together, we will solve the problem

**Comment by Juuxel** [comment]
I found the mod that causes the `getSoundGroup` crash - "enderscape". They make unsafe modifications to the block code, which Adorn doesn't and can't really expect. You can direct that part of this issue to them: https://github.com/bunten2005/enderscape

**Comment by AmibeSkyfy16** [comment]
Thanks man, i checked the code and see this comment line "// this sucks and should be changed Thanks" Xd
