### ISSUE TITLE
Most recent version for 1.16.5 requires Kotlin version that does not exist for 1.16.5

### ISSUE THREAD

**Issue by defenestrationdude** [Juuxel/Adorn#225]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.14.2+ 1.16.5
- Minecraft: 1.16.5
- Fabric Loader: 0.12.5
- Fabric API: 0.42.0+ 1.16
- Kotlin: 1.6.1+kotlin.1.5.10

### Describe the bug
When attempting to use both the most recent 1.16.5 Adorn build from September and the most recent 1.16.5 Kotlin build from May, the game is unable to boot as Adorn expects a newer version of Kotlin than currently exists for 1.16.5.

### To Reproduce
1. Install the most recent (as of this writing) 1.16.5 builds for both Adorn and Kotlin.
2. Attempt to run the game.

### Expected behavior
The game to boot, and run both mods (alongside others I've added).

### Additional context *(Optional)*
I'm not sure whether a better fix would be for Adorn to have an update to use an older Kotlin version in older Minecraft, or for Kotlin to push an update to bring it's newer versions to older Minecraft.
[latest.log](https://github.com/Juuxel/Adorn/files/7606149/latest.log)
.

**Comment by Juuxel** [comment]
This is not a bug (at most a bug with your launcher if it doesn't let you download the latest FLK version).

Fabric Language Kotlin is fully version-agnostic and each version of FLK works on each MC version. FLK 1.6, which Adorn requires, can also be downloaded directly from here: https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/files/3477154
