### ISSUE TITLE
[1.16.5] fix for missing cross-mod compatibility textures

### ISSUE THREAD

**Issue by ghost** [Juuxel/Adorn#226]
block models misspelled, by this mistake textures does not load correctly.

**models:**
1. scoria_stonebrick_step.json
2. scoria_stonebrick_post.json
3. scoria_stonebrick_platform.json

`̶"̶t̶e̶x̶t̶u̶r̶e̶"̶:̶ ̶"̶b̶y̶g̶:̶b̶l̶o̶c̶k̶/̶s̶c̶o̶r̶i̶a̶_̶s̶t̶o̶n̶e̶b̶r̶i̶c̶k̶"`

`"texture": "byg:block/scoria_stone_bricks"`

MCv: **1.16.5**
Mv: **Adorn-1.14.2+1.16.5**

Regards,
CSSmc

**Comment by ghost** [comment]
[adorn.zip](https://github.com/Juuxel/Adorn/files/7622714/adorn.zip)

**Comment by Juuxel** [comment]
Thanks, I'll have a look if this still affects 1.17. Adorn for MC 1.16 is not supported anymore as it's an outdated Minecraft version, but I might make a final bug fix release for MC 1.17.

**Comment by lSherozl** [comment]
If its just a simple spelling mistake why can't it come out for the 1.16.5 version too, most of the downloads for this mod are from there
