### ISSUE TITLE
ModResolutionException on 1.18.1 Server

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Juuxel/Adorn#229]
Even though Adorn 3.0.0+1.18.1 runs fine the client, it does not run on a server

- Adorn 3.0.0+1.18.1
- Minecraft 1.18.1
- Fabric Loader: 0.12.11
- Fabric API: 0.44.0

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7706559/latest.log)

**Comment by Juuxel** [comment]
You have an outdated version of Minecraft. Your server is running 1.18, and Adorn requires 1.18**.1**.

**Comment by ClaudiusMinimus** [comment]
Thanks for catching that! My install script messed up. Likely it will run when I fix it. If it runs, then I will close this issue.

**Comment by ClaudiusMinimus** [comment]
Changing the install script to use Minecraft 1.18.1 fixed it.

Looks like I cannot close your issues, so you will need to do it.

Thanks!
CM
