### ISSUE TITLE
Crash when attempting to open containers

### ISSUE THREAD

**Issue by crysthala** [Juuxel/Adorn#23]
I really like this mod, it's a great way to spruce the place up a little. Unfortunately, I've been getting crashes when attempting to open any container from the mod. Something about the GUI system is making it mad. This is me loading up a test world and trying to open an acacia cabinet. Sometimes the game hangs and I have to have Windows end it, sometimes it just crashes to desktop.
[latest.log](https://github.com/Juuxel/Adorn/files/3439479/latest.log)
[crash-2019-07-28_13.45.33-server.txt](https://github.com/Juuxel/Adorn/files/3439477/crash-2019-07-28_13.45.33-server.txt)

Versions:
MC 1.14.4
Fabric 0.5.0.33 / loader 0.4.8 build 158
Fabric API 0.3.0-207
Fabric Language Kotlin 1.3.40+1
Adorn 1.2.0

I'm running lots of mods. If you suspect this is a conflict with another mod, please let me know and I'll try to figure out what it might be.

**Comment by Juuxel** [comment]
Thanks for reporting the bug!

I can't reproduce it with only Adorn, but could you try [this build](https://mega.nz/#!CcpEkYCQ!untTutGDGbmUg6gIlmBJCWg2Cx-NnkWD5ZBaXynVwMo)?

**Comment by crysthala** [comment]
Eureka! I'd been using an outdated version of Cotton (0.8.3-pre+1.14.3). Removing Cotton and its dependencies let it work fine. Adding the old Cotton in by itself broke it. Just tried it with the latest Cotton version on CurseForge and it's working fine again.

I had been using the old version because the new ones were crashing my game on startup. I guess that was actually one of Cotton's dependents freaking out about change, or something. Thanks for the help, and sorry to bother you! :)

**Comment by Juuxel** [comment]
Oh, that explains the issue (old Cotton includes an old version of LibGui that apparently overrides the actual LibGui). Anyways, thanks for reporting the bug! It could've been my fault as well :sweat_smile:
