### ISSUE TITLE
missing texture for obyg scoria stone (post, platform and step)

### ISSUE THREAD

**Issue by vincehedric05** [Juuxel/Adorn#235]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.14.2
- Minecraft: 1.16.5

### Describe the bug
missing texture for obyg scoria stone (post, platform, and step)

### To Reproduce
on recipe and REI

**Comment by Juuxel** [comment]
Adorn for outdated MC versions (including 1.16.5) isn't supported. If you run across this bug in a current version of MC, please report it though.
