### ISSUE TITLE
the server not respond on minecraft 1.18.1 (fabric 0.12.12)

### ISSUE THREAD

**Issue by zepool** [Juuxel/Adorn#239]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 3.2.0
- Minecraft: 1.18.1
- Fabric Loader: 0.12.12
- Fabric API: 0.46.0

### Describe the bug
A clear and concise description of what the bug is. **If your bug is a crash, attach the full game log (found in `logs/latest.log` after the game crashes.**

### To Reproduce
1. Go to 'host server minecraft'
2. Click on 'on'
3. Scroll down to 'For some reason, my 1.18 fabric server refuses to start up with this mod installed. It works just fine without it, but when I try to boot it up with this in the mods folder, immediately shuts itself off before it can start up. Is there a fix for this?'

### Expected behavior
For some reason, my 1.18 fabric server refuses to start up with this mod installed. It works just fine without it, but when I try to boot it up with this in the mods folder, immediately shuts itself off before it can start up. Is there a fix for this?

**Comment by Juuxel** [comment]
Try updating Fabric API to 0.46.1, which is what Adorn requires.

If that doesn't help, could you share the game log from logs/latest.log on github gist/pastebin?
