### ISSUE TITLE
Failed start because it

### ISSUE THREAD

**Issue by Mossy-Skies** [Juuxel/Adorn#240]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 
- Minecraft: 
- Fabric Loader: 
- Fabric API: 

### Describe the bug
A clear and concise description of what the bug is. **If your bug is a crash, attach the full game log (found in `logs/latest.log` after the game crashes.**

**Comment by Juuxel** [comment]
Please open another issue with the game log file attached as well as the versions filled out. I can't really help if I know nothing about it.
