### ISSUE TITLE
Game Crashes on start

### ISSUE THREAD

**Issue by Mossy-Skies** [Juuxel/Adorn#241]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 2.0.0+1.17
- Minecraft: 1.17.1
- Fabric Loader: 0.12.12-1.17.1
- Fabric API: 0.46.1-1.17.1

Whenever I try and run it (with just this mod in there) it crashes.
Crash log: 
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, version 0.29.0 or later.
	 - Replace mod 'LibGui' (libgui) 4.0.0+1.17 with any 4.x version that is compatible with:
Unmet dependency listing:
	 - Mod 'Adorn' (adorn) 2.0.0+1.17 requires version 0.29.0 or later of fabric, which is missing!
	 - Mod 'Adorn' (adorn) 2.0.0+1.17 requires any 4.x version of mod 'LibGui' (libgui), but only the wrong version is present: 4.0.0+1.17!
		 - Mod 'LibGui' (libgui) 4.0.0+1.17 is being provided through e.g. C:\Users\deadn\AppData\Roaming\.minecraft\mods\Adorn-2.0.0+1.17-fabric.jar -> META-INF/jars/LibGui-4.0.0+1.17.jar
Inactive mods:
	 - mod 'LibGui' (libgui) 4.0.0+1.17, reason: to replace
	 - mod 'LibNinePatch' (libninepatch) 1.1.0, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, version 0.29.0 or later.
	 - Replace mod 'LibGui' (libgui) 4.0.0+1.17 with any 4.x version that is compatible with:
Unmet dependency listing:
	 - Mod 'Adorn' (adorn) 2.0.0+1.17 requires version 0.29.0 or later of fabric, which is missing!
	 - Mod 'Adorn' (adorn) 2.0.0+1.17 requires any 4.x version of mod 'LibGui' (libgui), but only the wrong version is present: 4.0.0+1.17!
		 - Mod 'LibGui' (libgui) 4.0.0+1.17 is being provided through e.g. C:\Users\deadn\AppData\Roaming\.minecraft\mods\Adorn-2.0.0+1.17-fabric.jar -> META-INF/jars/LibGui-4.0.0+1.17.jar
Inactive mods:
	 - mod 'LibGui' (libgui) 4.0.0+1.17, reason: to replace
	 - mod 'LibNinePatch' (libninepatch) 1.1.0, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

1. Start game (with Adorn, Kotlin, and the API)
2. Wait a few seconds
3. See Error

### Expected behavior
The game should start normally (I played on 1.16.5 prior to this)

### Additional context *(Optional)*
This is probably really easy to solve, however I've tried to fix it on my own, so ignore my ignorance if this is easy!

**Comment by Juuxel** [comment]
It looks like
1. You don't have Fabric API in your mods folder at all (Fabric Loader can't find it)
2. Your Adorn is outdated as well, try updating to 2.3.1 (if you happen to have multiple adorn jars, remove the other versions)

**Comment by Mossy-Skies** [comment]
Ah, thank you! I could have sworn I had it in there!
