### ISSUE TITLE
Compatibility with Better Azalea? 

### ISSUE THREAD

**Issue by SargRReal** [Juuxel/Adorn#244]
Perhaps block compat with better azalea? It's a super niche mod but it's really nice and i feel would make a lot of people happy:D 
https://www.curseforge.com/minecraft/mc-mods/better-azalea

**Comment by Juuxel** [comment]
Coincidentally I added this in [today's update](https://www.curseforge.com/minecraft/mc-mods/adorn-for-forge/files/3638073), so it's already there if you update 😄

**Comment by SargRReal** [comment]
awesome!
