### ISSUE TITLE
Rotate counter top texture 90 degrees

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Juuxel/Adorn#247]
Lines of multiple countertops would look better if the lines in the andesite texture were horizontal when viewed from the front.

Side by side comparison with the counters from Builders Crafts and Additions: 
![2022-02-16_12 15 04](https://user-images.githubusercontent.com/18755309/154329539-b411f983-a8f6-47da-8aaf-5552357a4c0b.png)

**Comment by Juuxel** [comment]
This is semi-intentional. The problem with rotating the top texture is that corners and turns won't look as seamless, so I don't really want to do that.

**Comment by TheDeviantCrafter** [comment]
Point taken. This looks fairly strange. I guess I can always make my countertops face north/south.

![2022-02-16_12 46 55](https://user-images.githubusercontent.com/18755309/154334938-976b7cc7-fec9-4583-afcb-0e57264ddc8a.png)
