### ISSUE TITLE
adorn:stone_ladder rendering as vanilla minecraft_ladder 

### ISSUE THREAD

**Issue by PhilipOfMacedon** [Juuxel/Adorn#249]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 3.3.1
- Minecraft: 1.18.1
- Fabric Loader: 0.13.1
- Fabric API: 0.46.4

### Description
The stone ladder's held item model seems just fine:

![2022-02-20_14 20 55](https://user-images.githubusercontent.com/28969294/154855651-f621efb6-324f-498e-a5af-dd497dc69087.png)

But when you place the ladder onto a wall, although the F3 HUD says it's adorn:stone_ladder, it ends up using the exact same model as vanilla minecraft:ladder:

![2022-02-20_14 23 25](https://user-images.githubusercontent.com/28969294/154855732-817fc2c3-3a20-4683-b9d0-9b84965c81a8.png)

### Additional context: List of used mods

		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 2.2.1
		adorn: Adorn 3.3.1+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancementinfo: AdvancementInfo 1.18-fabric0.43.1-1.3
		alternatecurrent: Alternate Current 1.1.0
		animatica: Animatica 0.3+1.18
		appleskin: AppleSkin 2.3.0+mc1.18.1
		architectury: Architectury 3.6.17
		armorposer: Armor Poser 1.0.2
		artisanat: Artisanat 2.2.1
		autoconfig1u: Auto Config v1 Updated 3.2.2
		awesomedungeon: Awesome Dungeon 2.0.4
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.4
		betterbeds: Better Beds 1.2.0
		bettercommandblock: IDE Better Command Block 2.5.10
		bettercontrols: Better Controls 1.2.3
		betterfpsdist: Better FPS distance Mod 1.18-1.5
		bettermounthud: Better Mount HUD 1.1.4
		betterpingdisplay: Better Ping Display 1.1.1
		betterthirdperson: Better Third Person 1.6.0
		blockshifter: Blockshifter 1.4.1+fabric-1.18
		blue_endless_jankson: jankson 1.2.1
		borderlessmining: Borderless Mining 1.1.1+1.18
		bsvsb: Better Sodium Video Settings Button 2.0.5
		capes: Capes 1.2.2+1.18
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cem: Custom Entity Models 0.7.0
		citresewn: CITResewn 0.9.1+1.18.1
		clickmachine: Kenza's Click Machine 1.1.0
		cloth-api: Cloth API 3.1.61
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.1.61
		cloth-common-events-v1: Cloth Common Events v1 3.1.61
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.1.61
		cloth-scissors-api-v1: Cloth Scissors API v1 3.1.61
		cloth-utils-v1: Cloth Utils v1 3.1.61
		clumps: Clumps 8.0.0+5
		collective-fabric: Collective (Fabric) 4.5
		colytra: Colytra 2.1.0-1.18.1
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		completeconfig: CompleteConfig 1.3.3
		config2brigadier: Config to Brigadier 1.0.2
		continuity: Continuity 1.0.3+1.18
		cool_elytra: Cool Elytra 1.3.1
		craftpresence: CraftPresence 1.8.8
		cullleaves: Cull Leaves 2.3.2
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		dark-loading-screen: Dark Loading Screen 1.6.11
		darkness: True Darkness 2.0.89
		darkpaintings: DarkPaintings 9.0.3
		dawn: Dawn API 3.2.0
		decorative_blocks: Decorative Blocks 2.0.4
		diamondglass: DiamondGlass 4.5.30
		dirtnt: DirTNT 1.1.1-1.18
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18
		dynmus: Dynamic Music 1.4.1
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		entity_texture_features: Entity Texture Features 2.1.3
		exlineawnings: Exline's Awnings 1.18
		exlinefurniture: Exline's Furniture fabric-1.18.1-v2.0.4
		extra_tnt: Extra Tnt 1.0.5
		extrasounds: Extra Sounds 2.2.0+1.18
		eyemod: EyeMod 1.0
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabric-tree-chopper: Fabric Tree Chopper 0.8.4
		fabricloader: Fabric Loader 0.13.1
		fake-player-api: Fake Player API 0.3.0
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		ferritecore: FerriteCore 4.1.1
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		flytre_lib: FlytreLib 1.7.1
		fpsreducer: FPS Reducer 1.25-mc1.18
		g4mespeed: G4mespeed 1.2.4
		g4mespeed-capture-playback: G4mespeed Capture & Playback 0.3.1-beta
		geckolib3: Geckolib 3.0.32
		giantspawn-fabric: Giant Spawn (Fabric) 2.7
		glassdoor: Glass Doors 2.0.0-1.18
		graveyard: The Graveyard 1.5
		healthcare: Health Care 1.0.10
		healthoverlay: Health Overlay 6.0.1
		hidearmor: Hide Armor 2.5
		hwg: Happiness is a Warm Gun 1.0.2
		hyperlighting: Hyper Lighting 1.2.1
		icarus: Icarus 1.9
		indium: Indium 1.0.2-alpha2+mc1.18.1
		interference: Interference API 1.3.0
		iris: Iris 1.2.0-pre
		itemmodelfix: Item Model Fix 1.0.3+1.18
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.6
		lambdabettergrass: LambdaBetterGrass 1.2.2+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazy-language-loader: lazy-language-loader 0.2.6
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.3.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libraryferret: Library Ferret 1.0.3
		libzoomer: LibZoomer 0.3.0+1.17.1
		lifts: Lifts 1.4-BETA+1.18
		lightestlamp: Lightest Lamps 1.0.0-beta
		lithium: Lithium 0.7.7
		loadmyresources: Load My Resources 1.0.1
		mambience: MAmbience 4.0.3+1.18.1
		me_hypherionmc_night-config_core: core 3.6.5_custom
		me_hypherionmc_night-config_toml: toml 3.6.5_custom
		midnightlib: MidnightLib 0.3.1
		milk: Milk Lib 0.1.5
		milk_plus: Milk+ 2.0.1
		minecraft: Minecraft 1.18.1
		mo_glass: Mo Glass 1.6.1-MC1.18.1
		mobscarecrow: Mob Scarecrow 1.2.0
		modmenu: Mod Menu 3.0.1
		music_control: Music Control 1.5.3+1.18
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		notenoughanimations: NotEnoughAnimations 1.4.0
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.2.2-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		pandamc_concreteplus: Concrete Plus 1.9.2
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		pettable: Pettable 1.2.1
		pipe: Pipe 1.6.2
		plated: Plated 2.2.0
		pride: Pride Lib 1.1.0+1.17
		reborncore: Reborn Core 5.1.0-beta.9
		redbits: Red Bits 1.12.0
		roughlyenoughitems: Roughly Enough Items 7.2.425
		simple_shelves: Simple Shelves 1.0.4
		sit: Sit 1.18.1-16
		skinlayers: 3d Skin Layers 1.4.0
		smoothswapping: Smooth Swapping 0.4.4
		sodium: Sodium 0.4.0-alpha6+build.14
		soundcategories: Sound Categories 1.2.0+1.18
		spark: spark 1.8.6
		spruceui: SpruceUI 3.3.2+1.17
		starlight: Starlight 1.0.0+fabric.d0a3220
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.1.0-beta.9
		terrablender: TerraBlender 1.1.0.76
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		tnttime: TNT Time 1.0.0
		trapexpansion: Trap Expansion 1.3.3
		trinkets: Trinkets 3.2.0
		unobtainables: Unobtainables 0.1.0
		villagersleashed: Villagers Leasged 1.0
		warppipes: Warp Pipes 1.0.1
		waveycapes: WaveyCapes 1.0.4
		windchimes: Windchimes 1.2.0
		worldedit: WorldEdit 7.2.9+e20e013
		xaerominimap: Xaero's Minimap 22.1.2
		xaeroworldmap: Xaero's World Map 1.20.1
		yigd: You're in Grave Danger 1.2.18

**Comment by Juuxel** [comment]
This is a problem with your resource pack overriding the ladder model to use different texture variables so Adorn's textures don't apply.

**Comment by PhilipOfMacedon** [comment]
Wait, but I thought this mod's ladder had its own model, so how do I make them separate? Do I create a resource pack for adorn?

**Comment by Juuxel** [comment]
Adorn's ladder model has the vanilla ladder's model as its parent (`"parent": "minecraft:block/ladder"`). I guess you could just copy the vanilla model into `assets/adorn/models/block` in a resource pack and change the texture to point at `adorn:block/stone_ladder`.
