### ISSUE TITLE
1.18.2 compatibility?

### ISSUE THREAD

**Issue by BrekiTomasson** [Juuxel/Adorn#252]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 3.3.1
- Minecraft: Minecraft 1.18.2
- Fabric Loader: 0.13.3
- Fabric API: 0.47.9

Minecraft crashes on startup when attempting to load the latest version of Adorn under Minecraft 1.18.2.

**Comment by Juuxel** [comment]
I know, I haven't ported to 1.18.2 yet since I'm sadly in the middle of a feature update as well 😅

**Comment by BrekiTomasson** [comment]
Gotcha! No rush.

**Comment by TwixtedChaox** [comment]
How long until 3.4 release is ready? Can I build it now?
