### ISSUE TITLE
Better Azalea’s discontinuance, support for Ecologics

### ISSUE THREAD

**Issue by brnbrd** [Juuxel/Adorn#257]
Better Azalea has been discontinued as the mod was integrated into one by the same author—Ecologics. It follows that support for the wood types should continue with Ecologics rather than a discontinued mod.

**Comment by emoace** [comment]
There is also a Fabric version of Ecologics that merged with Better Azalea, if you feel like porting these changes to Fabric too.

**Comment by Juuxel** [comment]
Ecologics (Forge only) support was added in 45505e8e69fc2001fe5bfceaf0285937eb2b13c9 and Better Azalea support was removed, thanks for letting me know about the change!
