### ISSUE TITLE
Putting water in a sink causes game to crash.

### ISSUE THREAD

**Issue by Kfrost084** [Juuxel/Adorn#265]
### Versions of Minecraft, Forge and Adorn
- Adorn: 3.5.2+1.19
- Minecraft: 1.19
- Forge: 41.0.38

### Describe the bug
Placing water in a sink causes this crash: The game crashed whilst rendering block entity
Error: java.lang.NoSuchMethodError: 'net.minecraftforge.fluids.FluidAttributes net.minecraft.world.level.material.Fluid.getAttributes()'
Exit Code: -1
[crash-2022-06-17_17.03.22-client.txt](https://github.com/Juuxel/Adorn/files/8931682/crash-2022-06-17_17.03.22-client.txt)

### To Reproduce
1 Place down a sink.
2 Right click on sink with a water bucket.

### Expected behavior
Game shuts down and brings up the launcher with a game crash notice.

### Additional context *(Optional)*
Reloading the game results in the same crash upon Joining world. Loading the game without Adorn loads just fine. With Adorn I can still craft and place sinks, but once you place water in it again, same crash.

**Comment by Juuxel** [comment]
Thanks for reporting, fixed in 3.5.4.
