### ISSUE TITLE
Toasters and pressure plates crash game

### ISSUE THREAD

**Issue by dylanriesss** [Juuxel/Adorn#266]
When I put down 11 toasters in a line all with pressure plates and I activated them, the game crashes and now I'm unable to ever login to my world :( the crash report is as follows in the parenthesized link below↓.

[crash-2022-07-11_17.24.05-server.txt](https://github.com/Juuxel/Adorn/files/9087673/crash-2022-07-11_17.24.05-server.txt)

**Comment by Juuxel** [comment]
!Adorn doesn't have toasters, report to Sandwichable.
