### ISSUE TITLE
Crash on Forge 41.0.98 

### ISSUE THREAD

**Issue by jeyzzl** [Juuxel/Adorn#267]
The mod loads on server but not on client.
[crash-2022-07-13_15.35.26-fml.txt](https://github.com/Juuxel/Adorn/files/9105953/crash-2022-07-13_15.35.26-fml.txt)

**Comment by Juuxel** [comment]
Already fixed in dev (ab59f09e0a1a637a691c59346a58658e8995ee1b), just pending some testing and a release.
