### ISSUE TITLE
Blocks not placing correctly

### ISSUE THREAD

**Issue by DyingCookie** [Juuxel/Adorn#27]
When I place most adorn blocks, it turns into a carpet with a table on it. Sometimes waterlogged

**Comment by DyingCookie** [comment]
![image](https://user-images.githubusercontent.com/54159152/63134308-e89b4400-bf96-11e9-9c9c-8f58fb8366ed.png)

**Comment by Juuxel** [comment]
Could you post your full mod list?

**Comment by DyingCookie** [comment]
[mods.zip](https://github.com/Juuxel/Adorn/files/3512539/mods.zip)

**Comment by Juuxel** [comment]
Can you reproduce this with only Fabric API, Fabric Language Kotlin and Adorn?

**Comment by DyingCookie** [comment]
I doubt it, but im more confused as to why it isnt happening to anyone else

**Comment by Juuxel** [comment]
Does the problem still happen for you? I think it might be a registry issue. If it still happens, try deleting the `.fabric` folder next to the mods folder.

**Comment by Juuxel** [comment]
Closed due to no updates (feel free to make a new issue if it still happens).

**Comment by wnchstrboy** [comment]
I'm also having the exact same problem
