### ISSUE TITLE
Compatibility with techreborn, problem with recipes

### ISSUE THREAD

**Issue by methylenimine** [Juuxel/Adorn#271]
### Versions of Minecraft, Adorn
- Adorn: finded in 3.5.4 tested in 3.6.0 too
- Minecraft: 1.19
- TechReborn 5.3.2

### Describe the bug
Tech reborn compability problem. In listed files non existed item causing errors in recipe.
i think need to replace
"items": ["techreborn:rubber_plank_slab"]
to
"items":["techreborn:rubber_slab"]

no such item rubber_plank_slab

in files
Data/adorn/recipes/techreborn/rubber_bench.json
Data/adorn/recipes/techreborn/rubber_chair.json
Data/adorn/recipes/techreborn/rubber_coffee_table.json
Data/adorn/recipes/techreborn/rubber_drawer.json
Data/adorn/recipes/techreborn/rubber_platform.json
Data/adorn/recipes/techreborn/rubber_shelf.json
Data/adorn/recipes/techreborn/rubber_step.json
Data/adorn/recipes/techreborn/rubber_table.json

Data/adorn/advancements/recipes/techreborn/rubber_bench.json
Data/adorn/advancements/recipes/techreborn/rubber_chair.json
Data/adorn/advancements/recipes/techreborn/rubber_coffee_table.json
Data/adorn/advancements/recipes/techreborn/rubber_drawer.json
Data/adorn/advancements/recipes/techreborn/rubber_platform.json
Data/adorn/advancements/recipes/techreborn/rubber_shelf.json
Data/adorn/advancements/recipes/techreborn/rubber_step.json
Data/adorn/advancements/recipes/techreborn/rubber_table.json

at least my server loading with this errors and this furniture is not craftable at this moment.

**Comment by Juuxel** [comment]
Thanks for reporting, this is fixed in Adorn 3.6.1 (coming out later today).
