### ISSUE TITLE
[Request] Backport EMI support to 1.18.2

### ISSUE THREAD

**Issue by Pirogiran** [Juuxel/Adorn#273]
Would really like to see EMI compatibility in 1.18.2, if it's not too difficult, because since 3.6.0 (but it's only on 1.19) Adorn has EMI support.

**Comment by Juuxel** [comment]
Adorn for 1.18.2 doesn't get feature updates anymore since backporting large changes takes a lot of time.

**Comment by Pirogiran** [comment]
> Adorn for 1.18.2 doesn't get feature updates anymore since backporting large changes takes a lot of time.

It's not an issue anymore! I've already updated, because another mods been updated.
And thanks for reply!
