### ISSUE TITLE
different brewer UI

### ISSUE THREAD

**Issue by Kevinello** [Juuxel/Adorn#277]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 3.3.1
- Minecraft: 1.18.1
- Fabric Loader: 0.13.3
- Fabric API: 0.46.4

### Describe the bug
I can't use brewer with such UI:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/56342249/182218463-cfd62ba0-18b7-4ecc-b650-6dfc97892402.png">

### To Reproduce
1. just place brewer and enter the UI

### Expected behavior
UI like this
![image](https://user-images.githubusercontent.com/56342249/182218437-1c6e7ec2-e8c4-4e2f-a866-51f015e4de73.png)

### Additional context *(Optional)*
nothing

**Comment by Juuxel** [comment]
You are using Adorn 3.3 and fluid brewing was added in Adorn 3.4. In addition to that, I don't support Fabric 1.18 (especially 1.18.1 - update to 1.18.2).
