### ISSUE TITLE
Invocation Target Exception with latest version of Forge

### ISSUE THREAD

**Issue by Gamemassa** [Juuxel/Adorn#278]
### Versions of Minecraft, Forge and Adorn
- Adorn: 3.6.1
- Minecraft: 1.19.2
- Forge: 43.0.1

### Description
I got the following error message when launching with the latest version of Forge:

Exception message: java.lang.IncompatibleClassChangeError: Method 'net.minecraftforge.eventbus.api.BusBuilder net.minecraftforge.eventbus.api.BusBuilder.builder()' must be InterfaceMethodref constant

### Crash Report
https://gist.github.com/Gamemassa/6c86d301b8310d7e611c6fc71905d47a

**Comment by Juuxel** [comment]
Thanks for the report, I'll investigate this.

Note that this error might be a bug in Kotlin for Forge instead (the error is coming from [its code](https://github.com/thedarkcolour/KotlinForForge/blob/daddbbfdc0a18d5c1b903b98a8ba0584f7f273b1/kfflang/src/main/kotlin/thedarkcolour/kotlinforforge/KotlinModContainer.kt#L40)). If that's the case then I can't fix it in Adorn itself.

**Comment by Gamemassa** [comment]
Oh, if that's the case, I'll copy this thread and repost it in their GitHub as well. Please keep me posted though, and thanks for the quick response!

**Comment by Juuxel** [comment]
It seems that the issue was fixed in KFF 3.7.1 (thedarkcolour/KotlinForForge#46, thedarkcolour/KotlinForForge@b14c348). Could you try and see if updating to that version works?

**Comment by Gamemassa** [comment]
Good morning! I've just tested and I can confirm, the latest version of Kotlin does fix the issue. Thanks again!
