### ISSUE TITLE
Working Problems

### ISSUE THREAD

**Issue by ButThatScaresMe** [Juuxel/Adorn#28]
So Ive Installed The Mod Correctly But It Wont Show Furniture

**Comment by ButThatScaresMe** [comment]
Furniture Dosnt Show Up

**Comment by ButThatScaresMe** [comment]
downloaded correctly but wont show furniture please fix

**Comment by Juuxel** [comment]
What do you mean by "won't show furniture"? Is it not showing up in REI?

Also, what's your Minecraft, Fabric Loader and Fabric API version?

**Comment by Juuxel** [comment]
Closed for inactivity.
