### ISSUE TITLE
Issue with placing chairs above y=255

### ISSUE THREAD

**Issue by Radon000** [Juuxel/Adorn#280]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 3.5.0
- Minecraft: 1.18.2
- Fabric Loader: 0.14.8
- Fabric API: 0.57.0

### Describe the bug
When trying to place any type of adorn chair at or anywhere above y=255, nothing happens.

### To Reproduce
1. Go above y=255
2. Try to place any type of chair
3. See error

### Expected behavior
For the chair to be placed.

Blue line is y=255
![chairbug](https://user-images.githubusercontent.com/76611592/183825397-20e8cdf8-f142-41e2-b9aa-b3d5b99d0c48.jpg)

**Comment by Juuxel** [comment]
Thanks for reporting that, the culprit is this check from the 1.14 era:

https://github.com/Juuxel/Adorn/blob/2aaf03632b5b1679a8b6f0dce76e658ab107856e/common/src/main/kotlin/juuxel/adorn/block/ChairBlock.kt#L51

It's probably copied from vanilla code from that time so it needs fixing for current MC versions.

**Comment by Astraios117** [comment]
Is it possible to compile the 1.18.2 version jar with this removed? The new height limit is 319. I tried doing it from the source code but I could not

**Comment by Radon000** [comment]
I just replaced 255 with 319, rebuilt it, and it works perfectly.

**Comment by Astraios117** [comment]
> I just replaced 255 with 319, rebuilt it, and it works perfectly.

Could you post that jar here please, I couldn't figure out how to rebuild it for fabric. I've never compiled code before

**Comment by Radon000** [comment]
https://www.dropbox.com/s/1jwxsvm2uu1xoki/Adorn-3.5.0%2B1.18.2-%20fabric%20PATCHED.jar?dl=1
