### ISSUE TITLE
Sofa And Chair Sitting Glitch 

### ISSUE THREAD

**Issue by Njem17** [Juuxel/Adorn#281]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 3.6.1 for 1.19
- Minecraft: 1.19
- Fabric Loader: Fabric 0.14.8
- Fabric API: 1.19

### Describe the bug
When I go to sit in a chair or even sitting on any sofa I craft everything is fine, but if i log out of my game or disconnect, when i log back in my character is like not sitting down anymore, and it seems like ive fallen through the chair or sofa. I have to click the sofa/chair to bring myself up and out of it then im sitting back in it properly. Its almost like im totally out of the chair somehow. This happens every time. I am playing the DREAMCRAFT 1.19 FABRIC pack.

### To Reproduce
1. Go to Any chair or sofa to sit. 
2. Right click it to sit.
3.  Disconnect/logout from game
4. join/connect back into game and you will be under/inside the chair/sofa you were sitting on.

### Expected behavior
For my friend and I to sit and remain seated in the chair/sofa after joining/gettin back in game. 
![2022-08-22_190946](https://user-images.githubusercontent.com/111817196/186041089-4b92994f-6df7-4396-ae3f-dd4f2ad1c4d1.png)
![2022-08-22_191035](https://user-images.githubusercontent.com/111817196/186041109-ea8f452b-6565-4f5b-9995-3cc057d9685f.png)

**Comment by DagothUrTheFalse** [comment]
I am also experiencing this problem, any time I dismount i end up phasing through my floor, made pretty bad as my floor is all upper slabs above the ground.

**Comment by Juuxel** [comment]
Fixed in 322fd125758ec4330787f542b4d88b0325a821f0.
