### ISSUE TITLE
Drawers create a hole in the floor and sides of other blocks (Screenshot attached) / Sodium - Iris - Continuity - CITResewn etc.

### ISSUE THREAD

**Issue by OkinawaGaijin** [Juuxel/Adorn#284]
### Adorn version

3.6.1+1.19

### Minecraft version

1.19.2

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.14.9 - Fabric Api 0.60.0+1.19.2

### Describe the bug

Using the Oak Drawer, it removes a 4x16 pixel part of any floor directly below the protruding drawers, revealing the map below. They also remove sideparts of blocks next to them (look at the kitchen counter top next to the drawer to the left)

Running the game with Sodium / Iris (latest as of August 30) and using all recommended / required mods like Continuity and CITResewn to mimic Optifine capabilities. No other issues have been found so far with Adorn.

Placed the drawer on different surfaces and the result is the same, part of the blocks below disappear.

![2022-08-30_19 22 59](https://user-images.githubusercontent.com/109918869/187414943-e34b23e2-bd31-4744-8f02-bd36b06e3ec1.png)

### To reproduce

Just place the Drawer block somewhere.

I have not tested any other than the Oak Drawers, but I suspect the results to be the same for other types.

**Comment by Juuxel** [comment]
Thanks for the detailed bug report, I'll look into this. I suspect it's one of the rendering mods affecting the drawer rendering since it works normally without them.

**Comment by Juuxel** [comment]
I couldn't reproduce this with the mods mentioned in your description:
- Adorn+Fabric API+Fabric Language Kotlin
- Sodium
- Indium (needed for Continuity)
- Iris
- Continuity
- CIT Resewn

Could you share your full mod list?

**Comment by OkinawaGaijin** [comment]
I see. Be aware I'm using a total of 301 mods according to the main menu message. This also includes Immersive Portals, which currently has another huge bug when paired with Sodium. As long as I run a shaderpack on Iris, nothing happens, but if I turn the shaderpack off, the game crashes.

So I can't test the Adorn issue with shaderpacks turned off unless I disable ImmersivePortals

Several people who only use Sodium and Immersive Portal have already reported similar issues with crashlogs looking similar to mine.

Maybe it's not too far fetched to assume that the immersive portal mod is also somehow messing with the rendering related to your drawers.

I will give you my full modlist just to be on the safe side. Maybe you know of an incompatibility I missed. I also added in the Shaderpack and Resource Pack listing provided by one of my (unrelated) crash logs, just so you can see those too. Just note that I had the same issue without any resource packs touching vanilla textures too.

[Modlist_Latest.txt](https://github.com/Juuxel/Adorn/files/9452608/Modlist_Latest.txt)

**Comment by OkinawaGaijin** [comment]
Well, immersive portals updated to adapt to the latest Sodium version. The crash when trying to run them together without an Iris shader is gone.

But the drawer still looks botched.

But don't bother. With that long as hell modlist I'm running, there's bound to be some conflict that's causing it. I don't expect you to search for it. I'm not in the mood to A-B-Test my 300 mods either.

It's not a game-breaking issue, so I'll live with it.

**Comment by lostopkk** [comment]
I already sent the issue to the creator of moreculling, it happens with the moreculling mod, if you disable the option in the video settings it goes back to normal

https://github.com/fxmorin/MoreCulling/issues/92

**Comment by Juuxel** [comment]
Ah, another MoreCulling issue. There's nothing I can do to fix it then.

**Comment by FxMorin** [comment]
Could have given it the correct hitbox...

**Comment by Juuxel** [comment]
The hitbox is intentional and the correct outline is the full block.

I set [nonOpaque](https://github.com/Juuxel/Adorn/blob/873d0d829a8e6ee71fe3e33559db63009750c0b6/common/src/main/kotlin/juuxel/adorn/block/DrawerBlock.kt#L33) in the block settings which disables the culling in vanilla as expected for non-opaque blocks even if their outline shape is a full 1x1x1 cube, but MoreCulling breaks that behaviour.

**Comment by FxMorin** [comment]
Ya, MoreCulling goes more aggressive by using more data & caching. Since vanilla correctly implements hitboxes for all blocks, I'm able to instead do hitbox calculations to further cull all the missing blocks. It's fine if you don't want to support it tho

**Comment by Juuxel** [comment]
This will be fixed in Adorn 5.0.0, the next feature release.

**Comment by rinebergc** [comment]
@Juuxel Any chance we’ll see this fix backported to 1.19.2?
