### ISSUE TITLE
Biome Makeover Ancient Oak recipes missing

### ISSUE THREAD

**Issue by technotherion** [Juuxel/Adorn#288]
Willow, Balsa, Blighted Balsa, Swamp Cypress recipes are available for wooden Adorn items as expected, but Ancient Oak is missing. 

Minecraft 1.19.2
Doesn't show up in Just Enough Items, nor is it craftable when using the expected recipe for Kitchen Counter
Every Compat also installed
Using Fabric

**Comment by Juuxel** [comment]
This is a new wood type that Biome Makeover has added after I last updated the Biome Makeover support. I'll add it in a future update 🙂
