### ISSUE TITLE
[1.19.2 forge] Mud brick furniture's texture is broken

### ISSUE THREAD

**Issue by RedBeast1959** [Juuxel/Adorn#289]
### Adorn version

Adorn-3.6.1+1.19-forge.jar

### Minecraft version

1.19.2

### Mod loader

Forge

### Mod loader version

43.1.32

### Describe the bug

Adorn's mud brick step / post / platform's texture is broken( purple + black square thingy ).
Strangely, Adorn's mud brick variants item tag is about Biomes O' Plenty, even though mud brick is 1.19 vanilla block.

![2022-10-04_01 18 53](https://user-images.githubusercontent.com/100399264/193628579-dbdd89c3-e209-440c-bc47-ed4614fc95a1.png)

### To reproduce

1. Adorn with BiomesOPlenty-1.19.2-17.1.1.152.jar
2. Search and craft mud brick variants of Adorn( or just use creative mode or JEI )
3. Nightmarish purple black square!

### Additional context

By the way, Adorn's two books is unreadable for unknown reason. I use 223 mods, so It'll take time to seperate each mode to find bug's ground zero.

**Comment by Juuxel** [comment]
The issue is that I ported Adorn to 1.19 before BOP was out, so it still has the compatibility blocks for the old BOP mud blocks. I'll need to remove them.

**Comment by Juuxel** [comment]
Duplicate of #274.
