### ISSUE TITLE
1.19 Adorn Stone Torch Glitch

### ISSUE THREAD

**Issue by Pistolass** [Juuxel/Adorn#290]
### Adorn version

3.6.1

### Minecraft version

1.19

### Mod loader

Forge

### Mod loader version

Forge 41.0.113

### Describe the bug

The Stone Torch texture is glitched
![2022-10-06_15 39 45](https://user-images.githubusercontent.com/115168893/194342672-a9e02fa9-6ea5-4e78-8dc0-8b11af48fc26.png)

### To reproduce

Place the Stone Torch

### Additional context

I dont know if this is caused by some other mod on my mod list, but here goes a print of my mod list for context.
![image](https://user-images.githubusercontent.com/115168893/194343011-c13b31a9-38b5-4059-8e13-2c1c8417aca0.png)

**Comment by Juuxel** [comment]
I don't support OptiFine. If this bug still happens without it, please open a new issue.
