### ISSUE TITLE
Adorn books "Decorating Your Home" and "Trader's Manual" don't open GUI on Interaction in 1.19

### ISSUE THREAD

**Issue by jdwinters** [Juuxel/Adorn#292]
### Adorn version

3.61.

### Minecraft version

1.19.2

### Mod loader

Forge

### Mod loader version

43.1.47

### Describe the bug

When having either "Decorating Your Home" or "Trader's Manual" in hand and pressing the interact key, nothing happens.

### To reproduce

Use curseforge to create custom profile with Forge, add Adorn mod and dependencies, then create a new world and go into creative mode, grab the items mentioned earlier from the search.

**Comment by Juuxel** [comment]
Seems to have been fixed by my latest changes (not sure what was going on though), please comment/reopen if it occurs again after the next Adorn update.
