### ISSUE TITLE
Stone torch displays incorrectly when placed on a wall

### ISSUE THREAD

**Issue by TheBeav01** [Juuxel/Adorn#298]
### Adorn version

3.7.0

### Minecraft version

1.19.2

### Mod loader

Forge

### Mod loader version

Forge 43.1.57

### Describe the bug

**Demonstration of issue:** ![image](https://user-images.githubusercontent.com/31453946/205502350-38f18c68-4c4a-45d3-884f-3e67b532e61d.png)

**Mod List:** ![image](https://user-images.githubusercontent.com/31453946/205502330-d043c6ba-2daf-4a0c-9ed7-472935e1a230.png)

### To reproduce

Place a stone torch on any wall

### Additional context

This is the same issue as https://github.com/Juuxel/Adorn/issues/290 but I checked to see if it still happened without Optifine or Rubidium. It still happened, so I scaled back the mod list and it seems to be an issue with Adorn itself.

**Comment by Juuxel** [comment]
Thanks, I think I know now what causes it. Only `adorn:block/stone_torch` (not `wall_stone_torch`) includes `"render_type": "cutout"` in the model file, so Forge doesn't support transparent textures.
