### ISSUE TITLE
Creative Menu Crashes Game

### ISSUE THREAD

**Issue by Zykana** [Juuxel/Adorn#300]
### Adorn version

4.0.0

### Minecraft version

1.19.3

### Mod loader

Fabric

### Mod loader version

Latest

### Describe the bug

Game crashes when opening a creative menu.

### To reproduce

Open inventory in creative gamemode.

### Game logs

```text
<script src="https://gist.github.com/Zykana/298d2d850ede51e941fa2b120cd001c3.js"></script>
```

**Comment by Juuxel** [comment]
Thanks for the report! This will be fixed in Adorn 4.0.1.
