### ISSUE TITLE
1.9.3

### ISSUE THREAD

**Issue by Cheyyyz** [Juuxel/Adorn#302]
Even though there is a 1.9.3 version of this mod, Kotlin, required to run this mod, is still in 1.9.2 so I can't run the mod :( it doesn't seem they plan to update Kotlin is there another way to use this mod? I really like it.

**Comment by Juuxel** [comment]
Both Fabric Language Kotlin and Kotlin for Forge (depending on your mod loader) work on 1.19.3 from my experience.

Fabric Language Kotlin is marked as 1.19.3 compatible already, it doesn't depend on Minecraft.

I think the developer of Kotlin for Forge just forgot to mark the latest release as 1.19.3 compatible on CurseForge - [Kotlin for Forge 3.8.0](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files/4167046) is explicitly marked as 1.19.3 compatible too.
