### ISSUE TITLE
Parsing error loading recipe adorn:promenade/cherry_oak_table com.google.gson.JsonSyntaxException: Unknown item 'promenade:cherry_oak_slab'

### ISSUE THREAD

**Issue by milosworks** [Juuxel/Adorn#303]
### Adorn version

4.0.1

### Minecraft version

1.19.3

### Mod loader

Quilt

### Mod loader version

QFAPI 5.0.0-beta-6, QSL 4.0.0-beta-11, Quilt Loader 0.17.11

### Describe the bug

When trying to create a world i get a lot of errors:

### To reproduce

1. Try to create a world with default type world and cheats

### Game logs

```text
https://gist.github.com/VyrekXD/c7fcb11773dae7999b13007e712a3be3
```

**Comment by Juuxel** [comment]
The material ID seems to have changed in [Promenade 3.1](https://github.com/DawnTeamMC/Promenade/releases/tag/v3.1.0), so that needs adjusting.
