### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by Theoness1** [Juuxel/Adorn#304]
### Adorn version

Adorn-3.8.1+1.19.2-fabric

### Minecraft version

1.19.2

### Mod loader

Fabric

### Mod loader version

0.14.14

### Describe the bug

on all the textures of the mugs, there is an invisible pixel, not critical, but here ))

![bug](https://user-images.githubusercontent.com/89033436/220545918-84ed9ceb-0759-49d6-9f3f-3e06675480a4.png)

### To reproduce

View texture

**Comment by TH3N3WN00B** [comment]
Im also having some texture bugs in fabric 1.19.2 with fabric loader 0.14.17 and fapi 0.76.0

![2023-03-21_14 15 01](https://user-images.githubusercontent.com/10799738/226730605-2a9755a3-3d29-4801-9690-bcd1aeec8af6.png)
![2023-03-21_14 15 05](https://user-images.githubusercontent.com/10799738/226730612-a432e181-8753-4fee-b918-189db6190ca1.png)

**Comment by Juuxel** [comment]
@TH3N3WN00B That's a different bug, please open another issue with your full mod list.
