### ISSUE TITLE
[Fabric] Colormatic (custom color for ressource pack) broken by Adorn

### ISSUE THREAD

**Issue by ksorah1** [Juuxel/Adorn#305]
### Adorn version

Adorn 3.8.1 for 1.19.2

### Minecraft version

1.19.2

### Mod loader

Fabric

### Mod loader version

fabric-api-0.72.0+1.19.2, 0.14.14 loader

### Describe the bug

Carpets are white instead of red, with the mod installed. 

### To reproduce

Without Adorn I use Colormatic to get the "custom colors" features like Optifine but for fabric, and to get colored items (carpets for exemple), and biomes, with texturepacks like Patrix, that use this feature. 

When I use Adorn, Colormatic is not working anymore, carpets are white. 

It's not from fabric-language-kotlin-1.9.1+kotlin.1.8.10 (I tried it alone and all is working).

**Comment by ksorah1** [comment]
I addition, I can say that your furnitures are colored. 

Vanilla red carpet :
![2023-02-27 20_35_44-Minecraft_ 1 19 2 - Singleplayer](https://user-images.githubusercontent.com/112913359/221665057-7b327b70-46df-455b-bde7-da2cbf785850.jpg)
![2023-02-27 20_38_31-Minecraft_ 1 19 2 - Singleplayer](https://user-images.githubusercontent.com/112913359/221665628-97a8f888-06a0-47c5-8989-f011a9260a82.jpg)


Your pink sofa :
![2023-02-27 20_35_53-Minecraft_ 1 19 2 - Singleplayer](https://user-images.githubusercontent.com/112913359/221665171-1597973a-516d-4f48-958d-f2beaa65b5d8.jpg)

**Comment by ksorah1** [comment]
The red bed is working too.

**Comment by ksorah1** [comment]
Also I'm looking for somewhere to get the recipes, I don't find the brewing machine and the trading table anywhere.

**Comment by Juuxel** [comment]
You can find their recipes using the vanilla recipe book if you've found the ingredients, or with a recipe viewer such as EMI or REI.

You can also see the brewer's brewing recipes using either of those mods - Adorn supports both.

**Comment by ksorah1** [comment]
Thank you for your answer, I won't use EMI or REI because I wan't to keep my vanilla experience. 

RIP. 

What about the carpets ?

**Comment by Juuxel** [comment]
I can't reproduce this issue with Adorn + Colormatic + Iris + Patrix resource pack + Arc shader pack:
![](https://user-images.githubusercontent.com/6596629/221687861-43cd8af5-9583-4476-a995-2fccc3c7f4e6.png)

Are you sure you have no other mods affecting the rendering? Adorn shouldn't have any effect, actually.

**Comment by ksorah1** [comment]
Damn, I use those mods (the minimum) :
![2023-02-27 22_27_54-Fenêtre console de 1 19 2 fabric - MultiMC 5](https://user-images.githubusercontent.com/112913359/221689786-41b2bec1-8074-4a37-8d7e-4fc3bdd2f8bb.jpg)
I'm not actualy at home, I can't test more for now.

Sorry for the problem.

**Comment by ksorah1** [comment]
Now I'm at home but I don't know what I can try to turn it off, an idea ?

**Comment by Juuxel** [comment]
I'm not 100% sure, but try disabling Continuity since the resource pack also has connected textures for carpet. Those two features might interfere in this case.

**Comment by ksorah1** [comment]
You are right, that's continuity, the problem is that I need it or my game will be ugly :
![2023-02-27 23_05_55-Minecraft_ 1 19 2 - Singleplayer](https://user-images.githubusercontent.com/112913359/221696813-bf96d870-5f9d-4e5b-9c78-52ca29e63d31.jpg)
![2023-02-27 23_05_43-Minecraft_ 1 19 2 - Singleplayer](https://user-images.githubusercontent.com/112913359/221696848-afee57ed-438f-4637-ad29-ed658e7fec8f.jpg)

With continuity :
![2023-02-27 23_09_29-Minecraft_ 1 19 2 - Singleplayer](https://user-images.githubusercontent.com/112913359/221697187-95c5cf4f-c982-48f9-a17c-17bce629e751.jpg)

**Comment by Juuxel** [comment]
Not sure what could help then since this isn't related to Adorn at all. Maybe try asking from the authors of Colormatic/Continuity?

**Comment by ksorah1** [comment]
Yes but the problem happen only if I use Adorn.

**Comment by Juuxel** [comment]
I did some further investigation, and this can be reproduced without Adorn installed pretty easily by having a resource pack that contains a `blockstates` file where `minecraft:block/red_carpet` (for example) is used in a `multipart` definition.

[TestPack.zip](https://github.com/Juuxel/Adorn/files/10844800/TestPack.zip)

This pack reproduces the issue without Adorn, so it's not a bug in Adorn - just triggered by Adorn's (perfectly normal) block models.

**Comment by Juuxel** [comment]
This might be a case of kvverti/colormatic#84.

**Comment by ksorah1** [comment]
Arf and you sent them the link, thank you !

**Comment by ksorah1** [comment]
The guy just don't care, are you sure the problem is from his mod ?

**Comment by Juuxel** [comment]
Yes. It's mostly coincidentally present when Adorn is used since Adorn has some block models for its blocks that use the carpet models. The exact same thing can be caused by a resource pack. It's not something I can fix.

**Comment by ksorah1** [comment]
Ok thank you.
