### ISSUE TITLE
Duplication Glitch with Brewer

### ISSUE THREAD

**Issue by Mossy-Skies** [Juuxel/Adorn#309]
### Adorn version

3.8.2

### Minecraft version

1.19.2

### Mod loader

Fabric

### Mod loader version

Fabric Launcher 0.14.19 - Fabric API 0.76.0

### Describe the bug

Whenever someone is using the brewer, if they place an item in the bottom right slot, either by shift-clicking, or by placing it there manually, if they shift-click the object out it will duplicate the object.

### To reproduce

Place the brewer
Either fill up all the other slots or manually place [item; ie diamond] in the bottom right slot
Shift-Click diamond (singular)
Game returns Diamonds (2)

### Additional context

The game seems to dupe it in the following manor;

1 - 2 - 4 - 8

so on and so forth, you can do this until you have a stack of diamonds (or whatever other item that stacks).

If you want I can get an in-game recording of the glitch/bug

**Comment by Juuxel** [comment]
Thanks for the report, the bug is fixed in 3.8.3 and 4.1.1.
