### ISSUE TITLE
Crash with Experience Container!

### ISSUE THREAD

**Issue by MisterRickiy** [Juuxel/Adorn#31]
### Versions of Minecraft, Fabric and Adorn
- Adorn: Adorn-1.4.0+1.14.4
- Minecraft: 1.14.4
- Fabric Loader: fabric-loader-0.6.1+build.165-1.14.4
- Fabric API: fabric-api-0.3.2+build.218-1.14

### Describe the bug
When I install Adorn and 
Experience Container ( https://www.curseforge.com/minecraft/mc-mods/experience-container/files ) the game wont start. I can play Adorn alone with other mods but not with Experience Container.

### To Reproduce
1. Go to the Experience Container website, Adorn website and the Fabric-Api site and download this. Install this to the mods Folder.
2. Click on Minecraft.exe choose the Fabric Version and press Play.
3. See error

### Expected behavior
A clear crash, but nothing is in the Logs.

**Comment by Juuxel** [comment]
What version of Experience Container do you have? Also, could you post the game log that's generated right after the game crashes (`logs/latest.log` in your Minecraft instance folder)?

**Comment by MisterRickiy** [comment]
Hello, I play the Version [Experience Container 1.4]. I can reproduce the log in few days.

**Comment by Juuxel** [comment]
Cannot reproduce with Experience Container 1.4. Have you downloaded the 1.15 version by accident?
