### ISSUE TITLE
Crash with EMI v1.0.0

### ISSUE THREAD

**Issue by Gronglegrowth** [Juuxel/Adorn#312]
### Adorn version

3.8.3

### Minecraft version

1.19.2

### Mod loader

Fabric

### Mod loader version

Loader: 0.18.10 / QFAPI: qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2

### Describe the bug

On viewing brewer recipes in EMI, the game crashes.

### To reproduce

1. Look up a recipe in EMI involving the Brewer
2. Switch to the Brewer tab if it isn't active already
3. Game crashes

### Game logs

```text
Pasted here https://mclo.gs/3ujGkI0
```

### Additional context

EMI is version 1.0.0.

**Comment by Juuxel** [comment]
Fixed in 4566a7fd949e9a218dc582649415a8d4d89e7bbc.
