### ISSUE TITLE
If it doesn't exist already, add inexhaustable trading stations for server admins.

### ISSUE THREAD

**Issue by GoldenFurredFox** [Juuxel/Adorn#317]
The ability to create a server shop with inexhaustible trades would be really great for multiplayer modpack servers and also singleplayer map devs. It'd be a great way to incentivize an equal currency trade as well.

Also, if it does already exist, then you might want to actually complete the wiki and/or offer a community Discord server for users to ask questions in so that the GitHub doesn't receive more suggestions that have already been added.

**Comment by Juuxel** [comment]
I'm planning to do a trading station-focused feature update at some point so this would be part of that. This idea was also mentioned in #78.

As for the wiki, I had just accidentally left the default page on. Adorn has in-game docs for all its features.

Also, I don't mind people asking questions here on GH, it helps me keep track of them :sweat_smile:
