### ISSUE TITLE
[Crash]Crash in Minecraft 1.19.3 with Fabric Adorn mod 4.1.1+

### ISSUE THREAD

**Issue by ghost** [Juuxel/Adorn#318]
### Adorn version

4.1.1+

### Minecraft version

1.19.3

### Mod loader

Fabric

### Mod loader version

0.14.21 0.76.1

### Describe the bug

Crash during initialization

### To reproduce

[crash-2023-06-25_14.34.21-client.txt](https://github.com/Juuxel/Adorn/files/11859022/crash-2023-06-25_14.34.21-client.txt)

**Comment by Juuxel** [comment]
This appears to be a mixin error from the mod `pca-1_19_3` ("Plusls Carpet Addition"). This means that that mod's mixins are failing to modify Minecraft code used by Adorn, which then triggers the crash during Adorn's launch process.
