### ISSUE TITLE
Candlelit Lanterns Not Dropping

### ISSUE THREAD

**Issue by fzzyhmstrs** [Juuxel/Adorn#319]
### Adorn version

5.0.0

### Minecraft version

1.20.1

### Mod loader

Fabric

### Mod loader version

0.14.21

### Describe the bug

Candlelit lanterns don't appear to drop anything, no matter what tool (or bare hand) you try with.

They are set up to require a tool, but don't seem to have been given a tool they work with.

### To reproduce

1. Install adorn
2. Place candlelit lanterns
3. Try to break with fist. No drops
4. Try to break with pickaxe. No drops.
5. Repeat for all tools and a sword. No drops :(

### Game logs

```text
I didn't see anything relevant in the logs, like a tag error etc. No errors at all.
```

### Additional context

From peeking at code, it looks like the Candlelit Lantern Block is defined as needing a tool, but which tool is never defined.

Loot table doesn't seem to be the issue. Emi Loot says no conditions at all, which is... not quite true (needs to survive an explosion), but basically true.
![image](https://github.com/Juuxel/Adorn/assets/72876796/5545ade8-1239-40fd-b60d-a6672dd5c6c9)

Problem seems to be with the block settings requiring a tool
![image](https://github.com/Juuxel/Adorn/assets/72876796/f987f8a6-e665-4619-b649-b2f0c079caeb)

But not being put in a tool tag. I'd expect `adorn:candlelit_lanterns` here (pickaxe tag, but also looked in axe tag).
![image](https://github.com/Juuxel/Adorn/assets/72876796/71d6b262-0729-41ca-bf0e-cb2027bb33fb)

**Comment by Juuxel** [comment]
Thanks for the detailed report! Fixed in the next release.
