### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by bucktarded** [Juuxel/Adorn#32]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.4.1
- Minecraft: 1.14.4
- Fabric Loader: 0.6.2 build.166
- Fabric API: 0.3.2 build.266

### Describe the bug

My game's crashing on launch. Not even a sneeze before receiving "Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!" I've already tested this with and without the other mods that I use, as well.

### To Reproduce

1. Go to CurseForge and download Adorn, then install it.
2. Click on the Minecraft launcher, use the Fabric profile, and hit 'play'.
3. See error.

### Expected behavior

I expected for the game to not crash? lol

### Additional context *(Optional)*

[here's the crash log](https://github.com/Juuxel/Adorn/files/3636504/crash-2019-09-20_09.49.36-client.txt)

**Comment by Juuxel** [comment]
Thanks for reporting the crash! I think I know what causes it. I can publish a fix in a few days.

**Comment by bucktarded** [comment]
Great to hear! Thank you very much. :)
