### ISSUE TITLE
Xray possible using coffee table

### ISSUE THREAD

**Issue by purejosh** [Juuxel/Adorn#323]
### Adorn version

Adorn-3.9.1+1.19.2-fabric.jar

### Minecraft version

1.19.2-fabric

### Mod loader

Fabric

### Mod loader version

0.14.22

### Describe the bug

![image](https://github.com/Juuxel/Adorn/assets/70633949/8fc4b2ba-5123-4474-a4a5-c248cdfaf3c7)

### To reproduce

Pretty self explanatory. 

### Additional context

Is the cutout set correctly for the table?

**Comment by Juuxel** [comment]
Are you using MoreCulling?

**Comment by purejosh** [comment]
Wow, quick call out for that. Yeah, I am!

**Comment by Juuxel** [comment]
Then this is a duplicate of #284, which has been fixed for MC 1.20.1. (No guarantees on backports currently)

**Comment by purejosh** [comment]
Ah, thought I searched already but I didn't see that issue before. No worries about a backport, this was more for you than it was for us. Thanks!
