### ISSUE TITLE
Sitting bug

### ISSUE THREAD

**Issue by KBMC1364** [Juuxel/Adorn#327]
### Adorn version

Adorn-3.5.0+1.18.2-forge

### Minecraft version

1.18.2

### Mod loader

Forge

### Mod loader version

40.2.10

### Describe the bug

When you sit on a server if anyone logs out and logs back in they will see you stuck in place with a shaky head 

### To reproduce

1.Sit on any adorn chair
2.Have 2nd person log out and back in
3.Have the one sitting turn their head so the shaking is visible
4.Optional, break the chair under them and they will be floating

### Additional context

Video:https://cdn.discordapp.com/attachments/1048639482628415569/1152308553042907147/recording-2023-09-15_21.21.08.webm

**Comment by Juuxel** [comment]
1.18 is not supported.
