### ISSUE TITLE
downdate adorn 5.1.0 to 1.20.1

### ISSUE THREAD

**Issue by peow** [Juuxel/Adorn#331]
could you make version 5.1.0 available for Minecraft 1.20.1? all my mods are in this version

**Comment by Juuxel** [comment]
I'll most likely make a new 5.0 patch update that contains the bug fixes. They're pretty small so it shouldn't be too much work.

In general, I don't backport features (which 5.1.0 doesn't happen to have) as maintaining multiple copies of the codebase between Minecraft versions takes a lot of time (the same code doesn't always work in all versions).
