### ISSUE TITLE
Update Candlelit Lanterns 1.19.2

### ISSUE THREAD

**Issue by burghenby** [Juuxel/Adorn#337]
I'm new to Github posting and feel a bit awkward posting this, so I apologize if I do this incorrectly.

As was mentioned in issue #319 the Candlelit Lanterns aren't mineable by any tool and they don't drop themselves once broken. The original issue specifically pointed at 1.20.1, though, and looking at the code it seems this was only fixed for that version up. I'm on 1.19.2 and I attempted to fix it on my own with a datapack with what I've been learning recently. However, I can't seem to get the tag fixed for the lanterns so there must be some structure to the mod, itself, that is beyond my understanding yet.

I wasn't sure if this should have been posted as a bug (since it was known because of the earlier issue) or an enhancement. I don't normally like to post requests and prefer to figure things out, myself, if I can. Just personal reasons, is all. >.<

**Comment by Juuxel** [comment]
Hi! I probably won't publish a new release for 1.19.2 as updating old versions is a bit of work due to tooling changes. I isolated the fix of #319 into a data pack, so can you see if it works?

[adorn-1.19.2-fix.zip](https://github.com/Juuxel/Adorn/files/14143170/adorn-1.19.2-fix.zip)

**Comment by burghenby** [comment]
Yes, it did! Thank you for your help, I really appreciate it. I was wracking my brain for hours trying to figure it out and just could not for the life of me figure out why I couldn't get it to work. Looking at your fix, I still don't understand what is different between yours and mine but I'm just glad it works. ^^
