### ISSUE TITLE
tutorial book linked with white wool

### ISSUE THREAD

**Issue by peow** [Juuxel/Adorn#342]
### Adorn version

5.0.1+1.20.1

### Minecraft version

1.20.1

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.15.7 / Fabric Api 0.92.0

### Describe the bug

whenever I create a world and get a white wool for the first time, I receive a tutorial book, how do I turn this off?
![2024-03-26_21 46 59](https://github.com/Juuxel/Adorn/assets/105888751/9fd6e86c-f4bf-46b9-be26-c7556d335fce)
![2024-03-26_21 47 03](https://github.com/Juuxel/Adorn/assets/105888751/53619943-6c6e-4d96-ab14-87058770c99b)

### To reproduce

1 - go to creative
2 - get a white wool

**Comment by Juuxel** [comment]
It's linked with the root advancement in Adorn's advancement page:
https://github.com/Juuxel/Adorn/blob/db15e7de9f578bfb027a0544efb053b709bed86f/common/src/main/resources/data/adorn/advancements/root.json#L14-L28

You can remove it by making a data pack where the reward isn't there. Sadly, I don't think there's any way to disable the reward of advancements based on the game mode (I would turn it off for creative in that case).

**Comment by peow** [comment]
hmm, okay, i think i will use a mod to remove the guide book from the game
