### ISSUE TITLE
Crafting crafting table

### ISSUE THREAD

**Issue by thefoxwhogotmilk** [Juuxel/Adorn#36]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.5.0
- Minecraft: 1.14.4
- Fabric Loader: 
- Fabric API: fabric-api-0.4.0+build.240-1.14

### Describe the bug
Can't craft the crafting table in inventory or even on a crafting table. Placing the wood and there is nothing to take.

### To Reproduce
1. Click "E"
2. Try to produce the crafting table
3. See error

### Expected behavior
A crafting table

**Comment by Juuxel** [comment]
Could you post the game log?

**Comment by PixelatedBruh** [comment]
The recipe has changed. I guess this is unintentional. 
![2019-10-17_19 26 44](https://user-images.githubusercontent.com/54760551/67061128-2130d880-f114-11e9-958d-23ce19bfbfda.png)
![2019-10-17_19 26 53](https://user-images.githubusercontent.com/54760551/67061133-24c45f80-f114-11e9-892d-c8eb627b8640.png)

**Comment by Boundarybreaker** [comment]
This is a bug with LibCD. It's fixed with the newest version, 1.4.0: https://www.curseforge.com/minecraft/mc-mods/libcd/files/2810008

**Comment by Juuxel** [comment]
Fixed in Adorn 1.5.1 which includes LibCD 1.4.0.
