### ISSUE TITLE
crashes on boot

### ISSUE THREAD

**Issue by EHE2** [Juuxel/Adorn#37]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.5.1
- Minecraft: 1.14.4
- Fabric Loader: 0.6.3 build 167
- Fabric API: 0.4.1 build 245

### Describe the bug
When launching the game through minecraft launcher on the fabric profile it immediately goes to a crash screen

### To Reproduce
1. Go to minecraft launcher
2. Select the fabric profile
3. Click Play
4. Get crash message

### Expected behavior
Game to launch to main menu

### Additional context *(Optional)*
I don't have many mods, and none of them should be conflicting
Mods:
Adorn (causes crash, works without adorn)
Fabric API
Fabric Mod Menu
Optifabric (with optifine)
Presence Footsteps
Trees Do Not Fall Down

### Images:
https://i.imgur.com/9FOfZ8I.png
https://i.imgur.com/KgLmXa7.png

**Comment by Juuxel** [comment]
Could you post the crash report on Pastebin or GitHub Gist and link it here? There's not much I can do without.

**Comment by EHE2** [comment]
That was dumb of me, you're right. I did check logs earlier and saw my problem, came on and saw you posted this haha. Thanks!
