### ISSUE TITLE
Terrestria and Traverse kitchen sink recipes accept any kitchen counters

### ISSUE THREAD

**Issue by Juuxel** [Juuxel/Adorn#53]
![report on CurseForge](https://user-images.githubusercontent.com/6596629/71309102-a4b8bf80-240c-11ea-89fc-bad99191068b.png)

**Comment by Trnrr** [comment]
Im running
- Adorn-1.6.2+1.15.1.jar
- traverse-2.1.4+build.10.jar
- terrestria-1.1.1+build.18.jar

In console I get these errors and cannot craft those items https://gist.github.com/Trnrr/9405bb0b2d6e8f369ab19575a9fe07ac

**Comment by Juuxel** [comment]
@Trnrr: Thanks for reporting that. Looks like my fix made another bug 😅
