### ISSUE TITLE
Conflict with 1.7.0 of Adorn with Lithium

### ISSUE THREAD

**Issue by pjlasl** [Juuxel/Adorn#56]
### Versions of Minecraft, Fabric and Adorn
- Adorn: Adorn-1.7.0+1.15.2
- Minecraft: 1.15.2
- Fabric Loader: fabricloader@0.7.5+build.178
- Fabric API: fabric-api-0.4.29+build.290-1.15.jar

### Describe the bug
There seems to be a conflict between the latest version of Adorn with Lithium. I previously had 1.6.3 with Lithium (lithium-mc1.15.2-fabric-0.3.1) and no errors occurred.

### To Reproduce
1. Include lithium-mc1.15.2-fabric-0.3.1 and Adorn-1.7.0+1.15.2 in the mods folder and startup.

### Expected behavior
Expected Lithium and Adorn for function together, like it did using 1.6.3 of Adorn.

### Additional context *(Optional)*
https://paste.ee/p/d85H6#3xVyFbTesVfPKpiI2DToaed9nKmyMKxe

**Comment by walkeraguilar** [comment]
I have the same problem, please can you fix that, many many thanks for the help.

You are great developer.

**Comment by Juuxel** [comment]
Fixed in f9e62b9c / 1.7.1.

**Comment by pjlasl** [comment]
I downloaded the update and loaded without issues alongside lithium.
