### ISSUE TITLE
Trading Station Owner cannot pick it up again.

### ISSUE THREAD

**Issue by Yungsaas** [Juuxel/Adorn#57]
So I tried the trading station and it works perfectly. Except that I cant pick it up again. Once its placed it is like bedrock and I cant get  rid of it again. Maybe add a function so that empty trading stations (without any items in them) can be picked up by the owner by sneak right clicking or something like that.

**Comment by Juuxel** [comment]
Trading station owners can always break the station blocks. You can also set the `protectTradingStations` config option to false on both the server and the client.

**Comment by Binero** [comment]
@Juuxel I was able to reproduce this. I cannot remove a trading station I placed down.

**Comment by superon** [comment]
can this be fixed?

**Comment by Juuxel** [comment]
This doesn't affect up-to-date versions of Adorn (2.0 and newer), where this functionality was completely replaced because of this bug. Older versions aren't supported anymore.
