### ISSUE TITLE
incompatible with Extra Pieces

### ISSUE THREAD

**Issue by Linguardium** [Juuxel/Adorn#64]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.8.0
- Minecraft: 1.15.2
- Fabric Loader: 0.7.8 build 188
- Fabric API: 0.5.0 build 293
- Extra Pieces: 2.8.3

### Describe the bug
Crashes on load when Adorn is loaded along side Extra-Pieces
https://www.curseforge.com/minecraft/mc-mods/extra-pieces
https://www.curseforge.com/minecraft/mc-mods/adorn

**Comment by Juuxel** [comment]
Could you post the crash log?

**Comment by Linguardium** [comment]
https://pastebin.com/RHBWLMXL

**Comment by Juuxel** [comment]
Fixed.
