### ISSUE TITLE
Bees/Villagers cant path around Adorn things

### ISSUE THREAD

**Issue by fatlard1993** [Juuxel/Adorn#66]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.8.1
- Minecraft: 1.15.2
- Fabric Loader: 0.7.8
- Fabric API: 0.5.1

### Describe the bug
Trying to use picket fences or wooden posts around a garden is disastrous. The poor little bees just get stuck when trying to path through an Adorn thing.. The villagers have a similar problem getting around town with them in the way.

### To Reproduce
1. Put posts, or fences from Adorn in the bees/villagers way and see them get stuck indefinitely, though untested I believe all Adorn items to behave the same

### Expected behavior
Bees/Villagers path around Adorn things and go about their business

**Comment by Linguardium** [comment]
this seems to be handled by AbstractBlock$canPathfindThrough in 1.16.1 which would check if they are full blocks, and if not, attempt to pathfind through them. 
might be something to look into

**Comment by Juuxel** [comment]
@Linguardium Thanks for the analysis, I think making that return false (like many vanilla blocks) should fix it.
