### ISSUE TITLE
Cake floating upon the Coffe Table

### ISSUE THREAD

**Issue by lucasfelipe-sh** [Juuxel/Adorn#71]
### Versions of Minecraft, Fabric and Adorn
- Adorn: Adorn 1.8.4
- Minecraft: 1.15.2
- Fabric Loader: 0.8.2 build 194
- Fabric API: 0.5.1 build.294-1.15

### Describe the bug
When I put a Cake upon the Coffe Table, the Cake does float upon the Coffe Table.

### To Reproduce
1. Place a Cake upon the Coffe Table
4. Watch it happening

### Expected behavior
Here's an image of what's supposed to happen: 
https://ibb.co/ZKPZ93s

**Comment by Juuxel** [comment]
This is a quirk of vanilla, not a bug (especially an Adorn one).
