### ISSUE TITLE
Chairs dropping two items when broken (item doubling)

### ISSUE THREAD

**Issue by RusticKey** [Juuxel/Adorn#79]
### Versions of Minecraft, Fabric and Adorn
- Adorn: v.1.8.4+1.15.2
- Minecraft: 1.15.2
- Fabric Loader: v0.8.4+build.198
- Fabric API: v0.11.1+build.312-1.15

### Describe the bug
When chairs are broken, they drop two items instead of one.

### To Reproduce
1. Go craft any chair
2. Destroy the chair (either top or bottom block)
3. Pick up the items dropped

### Expected behavior
The amount of chair should be doubled

**Comment by Juuxel** [comment]
Can't reproduce with Adorn 1.8.4. This might be a compatibility issue with another mod, or you might have a data pack that breaks the loot tables.

**Comment by Linguardium** [comment]
I am also running into this issue but only when you break the bottom half of the chair
