### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by DanShu15** [Juuxel/Adorn#81]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.8.4+1.15.2
- Minecraft: 1.15.2
- Inventory Profiles: https://github.com/jsnimda/Inventory-Profiles/issues/6
- Fabric API: 12.0 build 313-1.15

### Describe the bug
When using the sort inventory buttons inside an Adorn cupboard or container an exception is shown in the log and the inventory tries to sort, but an item is placed on your mouse cursor and the process doesn't complete

### To Reproduce
1. Go to 'any adorn cupboard'
2. Click on 'the sort inventory button'

**Comment by Juuxel** [comment]
Could you post the error log in a gist or on pastebin?

**Comment by DanShu15** [comment]
yes, let me get someone online that has a cupboard already set up and I'll clear my error log and have them reproduce

**Comment by DanShu15** [comment]
The log wasn't very large yet today so rather than a clear I just had someone test it
Server log:
https://pastebin.com/tNWiLeQK

**Comment by Juuxel** [comment]
Ah yes, a LibGui bug. I'll take a look at this at some point.

**Comment by Juuxel** [comment]
Fixed in LibGui.
