### ISSUE TITLE
Server crash opening drawers GUI

### ISSUE THREAD

**Issue by tambry** [Juuxel/Adorn#83]
### Versions of Minecraft, Fabric and Adorn
- Adorn: Adorn-1.8.6+1.16-rc1.jar
- Minecraft: 1.16
- Fabric Loader: 0.6.1.45
- Fabric API: 0.13.1+build.370-1.16

### Describe the bug
Server crashes if opening drawers on a dedicated server.

### To Reproduce
1. Start a dedicated server
2. Place oak drawers
3. Try to open the drawers GUI
4. Server crashes

[latest.log](https://github.com/Juuxel/Adorn/files/4825916/latest.log)

**Comment by Juuxel** [comment]
> libgui@2.0.0-beta.4+1.16-pre8

Remove any manually downloaded LibGui jar files; mods (including Adorn) bundle the latest one that fixed the problem.
