### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by cerealn** [Juuxel/Adorn#89]
I got this when trying to open the game. (I use 1.14.4)
[crash-2020-07-30_01.21.51-client.txt](https://github.com/Juuxel/Adorn/files/4998969/crash-2020-07-30_01.21.51-client.txt)

**Comment by Juuxel** [comment]
1.14.4 is outdated and not supported. You could try using the 1.16.1 version instead, it shouldn't have this bug.
