### ISSUE TITLE
Always generates Extra Pieces files regardless of config

### ISSUE THREAD

**Issue by StaticSapphic** [Juuxel/Adorn#91]
### Versions of Minecraft, Fabric and Adorn
- Adorn: 1.9.1
- Minecraft: 1.6.1
- Fabric Loader: 0.9.0+build.204
- Fabric API: 0.16.2+build.385

### Describe the bug
Disabling Extra Pieces in Adorn's config file still generates `adorn_vanilla_pieces.json`

### To Reproduce
0. Delete `adorn_vanilla_pieces.json` if it exists
1. Disable Extra pieces in `Adorn.json5`
2. Launch Minecraft
3. Look in `config\extrapieces\piecepacks`
4. `adorn_vanilla_pieces.json` has been recreated despite being disabled

### Expected behavior
Expected `adorn_vanilla_pieces.json` to not generate when extra pieces is disabled

**Comment by Juuxel** [comment]
This is something that Extra Pieces always copies itself. Since the actual support is not enabled when that config option is false, the file does effectively nothing.
